window.LANGUAGE_DNA_EVERYDAY_100 = [
  {
    "rank": 1,
    "english": "Hi",
    "spanish": "Hola",
    "category": "Greetings",
    "kind": "phrase",
    "exampleEn": "Hi!",
    "exampleEs": "¡Hola!",
    "family": "greeting",
    "morphology": "",
    "note": "Neutral and useful at any time of day.",
    "cefr": "A1",
    "usefulness": 100,
    "band": "Essential"
  },
  {
    "rank": 2,
    "english": "Good morning",
    "spanish": "Buenos días",
    "category": "Greetings",
    "kind": "phrase",
    "exampleEn": "Good morning, how are you?",
    "exampleEs": "Buenos días, ¿cómo está?",
    "family": "greetings",
    "morphology": "buenos / buenas",
    "note": "Use until around midday; exact habits vary by region.",
    "cefr": "A1",
    "usefulness": 99,
    "band": "Essential"
  },
  {
    "rank": 3,
    "english": "Good afternoon",
    "spanish": "Buenas tardes",
    "category": "Greetings",
    "kind": "phrase",
    "exampleEn": "Good afternoon.",
    "exampleEs": "Buenas tardes.",
    "family": "greetings",
    "morphology": "buenos / buenas",
    "note": "Used from after midday into the evening in many places.",
    "cefr": "A1",
    "usefulness": 98,
    "band": "Essential"
  },
  {
    "rank": 4,
    "english": "Good evening",
    "spanish": "Buenas tardes",
    "category": "Greetings",
    "kind": "phrase",
    "exampleEn": "Good evening.",
    "exampleEs": "Buenas tardes.",
    "family": "greetings",
    "morphology": "buenos / buenas",
    "note": "Spanish often uses buenas tardes where English uses good evening.",
    "cefr": "A1",
    "usefulness": 97,
    "band": "Essential"
  },
  {
    "rank": 5,
    "english": "Good night",
    "spanish": "Buenas noches",
    "category": "Greetings",
    "kind": "phrase",
    "exampleEn": "Good night, see you tomorrow.",
    "exampleEs": "Buenas noches, hasta mañana.",
    "family": "greetings",
    "morphology": "buenos / buenas",
    "note": "Can be a greeting at night or a goodbye before sleep.",
    "cefr": "A1",
    "usefulness": 96,
    "band": "Essential"
  },
  {
    "rank": 6,
    "english": "Goodbye",
    "spanish": "Adiós",
    "category": "Greetings",
    "kind": "phrase",
    "exampleEn": "Goodbye, see you soon.",
    "exampleEs": "Adiós, hasta pronto.",
    "family": "greetings",
    "morphology": "",
    "note": "Hasta luego is often a softer everyday alternative.",
    "cefr": "A1",
    "usefulness": 95,
    "band": "Essential"
  },
  {
    "rank": 7,
    "english": "Please",
    "spanish": "Por favor",
    "category": "Politeness",
    "kind": "phrase",
    "exampleEn": "A coffee, please.",
    "exampleEs": "Un café, por favor.",
    "family": "politeness",
    "morphology": "",
    "note": "Usually placed naturally at the end or beginning of a request.",
    "cefr": "A1",
    "usefulness": 94,
    "band": "Essential"
  },
  {
    "rank": 8,
    "english": "Thank you",
    "spanish": "Gracias",
    "category": "Politeness",
    "kind": "phrase",
    "exampleEn": "Thank you very much.",
    "exampleEs": "Muchas gracias.",
    "family": "politeness",
    "morphology": "gracias / muchas gracias",
    "note": "Gracias does not change for gender.",
    "cefr": "A1",
    "usefulness": 93,
    "band": "Essential"
  },
  {
    "rank": 9,
    "english": "You're welcome",
    "spanish": "De nada",
    "category": "Politeness",
    "kind": "phrase",
    "exampleEn": "You're welcome.",
    "exampleEs": "De nada.",
    "family": "politeness",
    "morphology": "",
    "note": "A very common response to gracias.",
    "cefr": "A1",
    "usefulness": 92,
    "band": "Essential"
  },
  {
    "rank": 10,
    "english": "Excuse me",
    "spanish": "Disculpe",
    "category": "Politeness",
    "kind": "phrase",
    "exampleEn": "Excuse me, where is the station?",
    "exampleEs": "Disculpe, ¿dónde está la estación?",
    "family": "politeness",
    "morphology": "disculpa / disculpe",
    "note": "Disculpe is polite/formal; disculpa is informal.",
    "cefr": "A1",
    "usefulness": 91,
    "band": "Essential"
  },
  {
    "rank": 11,
    "english": "Sorry",
    "spanish": "Lo siento",
    "category": "Politeness",
    "kind": "phrase",
    "exampleEn": "Sorry, I don't understand.",
    "exampleEs": "Lo siento, no entiendo.",
    "family": "politeness",
    "morphology": "",
    "note": "Use perdón for many quick apologies or interruptions.",
    "cefr": "A1",
    "usefulness": 90,
    "band": "Essential"
  },
  {
    "rank": 12,
    "english": "Yes",
    "spanish": "Sí",
    "category": "Basics",
    "kind": "word",
    "exampleEn": "Yes, please.",
    "exampleEs": "Sí, por favor.",
    "family": "yes / no",
    "morphology": "",
    "note": "The accent distinguishes sí (yes) from si (if).",
    "cefr": "A1",
    "usefulness": 89,
    "band": "Essential"
  },
  {
    "rank": 13,
    "english": "No",
    "spanish": "No",
    "category": "Basics",
    "kind": "word",
    "exampleEn": "No, thank you.",
    "exampleEs": "No, gracias.",
    "family": "yes / no",
    "morphology": "",
    "note": "Spanish no normally goes directly before the verb.",
    "cefr": "A1",
    "usefulness": 88,
    "band": "Essential"
  },
  {
    "rank": 14,
    "english": "Okay",
    "spanish": "De acuerdo",
    "category": "Basics",
    "kind": "phrase",
    "exampleEn": "Okay, let's go.",
    "exampleEs": "De acuerdo, vamos.",
    "family": "agreement",
    "morphology": "vale / de acuerdo",
    "note": "Vale is especially common in Spain; de acuerdo is widely understood.",
    "cefr": "A1",
    "usefulness": 87,
    "band": "Essential"
  },
  {
    "rank": 15,
    "english": "See you later",
    "spanish": "Hasta luego",
    "category": "Greetings",
    "kind": "phrase",
    "exampleEn": "See you later!",
    "exampleEs": "¡Hasta luego!",
    "family": "goodbyes",
    "morphology": "hasta + time",
    "note": "",
    "cefr": "A1",
    "usefulness": 86,
    "band": "Essential"
  },
  {
    "rank": 16,
    "english": "I",
    "spanish": "Yo",
    "category": "People",
    "kind": "word",
    "exampleEn": "I am here.",
    "exampleEs": "Yo estoy aquí.",
    "family": "pronouns",
    "morphology": "yo",
    "note": "Spanish often drops yo when the verb already makes the subject clear.",
    "cefr": "A1",
    "usefulness": 85,
    "band": "Essential"
  },
  {
    "rank": 17,
    "english": "Me",
    "spanish": "Me",
    "category": "People",
    "kind": "word",
    "exampleEn": "Can you help me?",
    "exampleEs": "¿Me puede ayudar?",
    "family": "object pronouns",
    "morphology": "me",
    "note": "",
    "cefr": "A1",
    "usefulness": 84,
    "band": "Essential"
  },
  {
    "rank": 18,
    "english": "You",
    "spanish": "Tú",
    "category": "People",
    "kind": "word",
    "exampleEn": "You are here.",
    "exampleEs": "Tú estás aquí.",
    "family": "pronouns",
    "morphology": "tú / usted",
    "note": "Tú is informal singular; usted is polite/formal in many contexts.",
    "cefr": "A1",
    "usefulness": 83,
    "band": "Essential"
  },
  {
    "rank": 19,
    "english": "He",
    "spanish": "Él",
    "category": "People",
    "kind": "word",
    "exampleEn": "He is my friend.",
    "exampleEs": "Él es mi amigo.",
    "family": "pronouns",
    "morphology": "él",
    "note": "The accent distinguishes él (he) from el (the).",
    "cefr": "A1",
    "usefulness": 82,
    "band": "Essential"
  },
  {
    "rank": 20,
    "english": "She",
    "spanish": "Ella",
    "category": "People",
    "kind": "word",
    "exampleEn": "She is here.",
    "exampleEs": "Ella está aquí.",
    "family": "pronouns",
    "morphology": "ella",
    "note": "",
    "cefr": "A1",
    "usefulness": 81,
    "band": "Essential"
  },
  {
    "rank": 21,
    "english": "We",
    "spanish": "Nosotros",
    "category": "People",
    "kind": "word",
    "exampleEn": "We are here.",
    "exampleEs": "Nosotros estamos aquí.",
    "family": "pronouns",
    "morphology": "nosotros / nosotras",
    "note": "Nosotras is used for an all-female group.",
    "cefr": "A1",
    "usefulness": 80,
    "band": "Essential"
  },
  {
    "rank": 22,
    "english": "They",
    "spanish": "Ellos",
    "category": "People",
    "kind": "word",
    "exampleEn": "They are here.",
    "exampleEs": "Ellos están aquí.",
    "family": "pronouns",
    "morphology": "ellos / ellas",
    "note": "Ellas is used for an all-female group.",
    "cefr": "A1",
    "usefulness": 79,
    "band": "Essential"
  },
  {
    "rank": 23,
    "english": "My",
    "spanish": "Mi",
    "category": "People",
    "kind": "word",
    "exampleEn": "My friend is here.",
    "exampleEs": "Mi amigo está aquí.",
    "family": "possessives",
    "morphology": "mi / mis",
    "note": "Mi becomes mis before plural nouns.",
    "cefr": "A1",
    "usefulness": 78,
    "band": "Essential"
  },
  {
    "rank": 24,
    "english": "Your",
    "spanish": "Tu",
    "category": "People",
    "kind": "word",
    "exampleEn": "Your hotel is near.",
    "exampleEs": "Tu hotel está cerca.",
    "family": "possessives",
    "morphology": "tu / tus / su",
    "note": "Tu is informal singular; su covers several polite/plural meanings.",
    "cefr": "A1",
    "usefulness": 77,
    "band": "Essential"
  },
  {
    "rank": 25,
    "english": "Friend",
    "spanish": "Amigo / amiga",
    "category": "People",
    "kind": "word",
    "exampleEn": "She is my friend.",
    "exampleEs": "Ella es mi amiga.",
    "family": "people",
    "morphology": "amigo / amiga / amigos / amigas",
    "note": "The ending commonly reflects gender.",
    "cefr": "A1",
    "usefulness": 76,
    "band": "Essential"
  },
  {
    "rank": 26,
    "english": "What?",
    "spanish": "¿Qué?",
    "category": "Questions",
    "kind": "word",
    "exampleEn": "What is this?",
    "exampleEs": "¿Qué es esto?",
    "family": "question words",
    "morphology": "qué",
    "note": "The accent marks the question form qué.",
    "cefr": "A1",
    "usefulness": 96,
    "band": "Very common"
  },
  {
    "rank": 27,
    "english": "Where?",
    "spanish": "¿Dónde?",
    "category": "Questions",
    "kind": "word",
    "exampleEn": "Where is the hotel?",
    "exampleEs": "¿Dónde está el hotel?",
    "family": "question words",
    "morphology": "dónde",
    "note": "The accent marks the question form dónde.",
    "cefr": "A1",
    "usefulness": 96,
    "band": "Very common"
  },
  {
    "rank": 28,
    "english": "When?",
    "spanish": "¿Cuándo?",
    "category": "Questions",
    "kind": "word",
    "exampleEn": "When do we eat?",
    "exampleEs": "¿Cuándo comemos?",
    "family": "question words",
    "morphology": "cuándo",
    "note": "",
    "cefr": "A1",
    "usefulness": 96,
    "band": "Very common"
  },
  {
    "rank": 29,
    "english": "Why?",
    "spanish": "¿Por qué?",
    "category": "Questions",
    "kind": "phrase",
    "exampleEn": "Why not?",
    "exampleEs": "¿Por qué no?",
    "family": "question words",
    "morphology": "por qué / porque",
    "note": "Por qué asks why; porque usually answers with because.",
    "cefr": "A1",
    "usefulness": 95,
    "band": "Very common"
  },
  {
    "rank": 30,
    "english": "Who?",
    "spanish": "¿Quién?",
    "category": "Questions",
    "kind": "word",
    "exampleEn": "Who is it?",
    "exampleEs": "¿Quién es?",
    "family": "question words",
    "morphology": "quién / quiénes",
    "note": "Quiénes is the plural form.",
    "cefr": "A1",
    "usefulness": 95,
    "band": "Very common"
  },
  {
    "rank": 31,
    "english": "How?",
    "spanish": "¿Cómo?",
    "category": "Questions",
    "kind": "word",
    "exampleEn": "How are you?",
    "exampleEs": "¿Cómo está?",
    "family": "question words",
    "morphology": "cómo",
    "note": "",
    "cefr": "A1",
    "usefulness": 95,
    "band": "Very common"
  },
  {
    "rank": 32,
    "english": "How much?",
    "spanish": "¿Cuánto?",
    "category": "Questions",
    "kind": "phrase",
    "exampleEn": "How much is it?",
    "exampleEs": "¿Cuánto cuesta?",
    "family": "quantity questions",
    "morphology": "cuánto / cuánta",
    "note": "",
    "cefr": "A1",
    "usefulness": 94,
    "band": "Very common"
  },
  {
    "rank": 33,
    "english": "How many?",
    "spanish": "¿Cuántos?",
    "category": "Questions",
    "kind": "phrase",
    "exampleEn": "How many people?",
    "exampleEs": "¿Cuántas personas?",
    "family": "quantity questions",
    "morphology": "cuántos / cuántas",
    "note": "Match gender: cuántos libros, cuántas personas.",
    "cefr": "A1",
    "usefulness": 94,
    "band": "Very common"
  },
  {
    "rank": 34,
    "english": "Where is...?",
    "spanish": "¿Dónde está...?",
    "category": "Questions",
    "kind": "phrase",
    "exampleEn": "Where is the bathroom?",
    "exampleEs": "¿Dónde está el baño?",
    "family": "where frames",
    "morphology": "dónde está / dónde están",
    "note": "Use están for plural things.",
    "cefr": "A1",
    "usefulness": 94,
    "band": "Very common"
  },
  {
    "rank": 35,
    "english": "What time is it?",
    "spanish": "¿Qué hora es?",
    "category": "Questions",
    "kind": "phrase",
    "exampleEn": "Excuse me, what time is it?",
    "exampleEs": "Disculpe, ¿qué hora es?",
    "family": "time questions",
    "morphology": "qué hora es",
    "note": "",
    "cefr": "A1",
    "usefulness": 93,
    "band": "Very common"
  },
  {
    "rank": 36,
    "english": "What is this?",
    "spanish": "¿Qué es esto?",
    "category": "Questions",
    "kind": "phrase",
    "exampleEn": "What is this?",
    "exampleEs": "¿Qué es esto?",
    "family": "question frames",
    "morphology": "qué es",
    "note": "",
    "cefr": "A1",
    "usefulness": 93,
    "band": "Very common"
  },
  {
    "rank": 37,
    "english": "Can you help me?",
    "spanish": "¿Me puede ayudar?",
    "category": "Questions",
    "kind": "phrase",
    "exampleEn": "Can you help me, please?",
    "exampleEs": "¿Me puede ayudar, por favor?",
    "family": "help requests",
    "morphology": "puedo / puede / ayudar",
    "note": "A polite useful request; ¿Puedes ayudarme? is informal.",
    "cefr": "A1",
    "usefulness": 93,
    "band": "Very common"
  },
  {
    "rank": 38,
    "english": "Do you speak English?",
    "spanish": "¿Habla inglés?",
    "category": "Questions",
    "kind": "phrase",
    "exampleEn": "Do you speak English?",
    "exampleEs": "¿Habla inglés?",
    "family": "language questions",
    "morphology": "hablo / hablas / habla",
    "note": "¿Hablas inglés? is informal singular.",
    "cefr": "A1",
    "usefulness": 92,
    "band": "Very common"
  },
  {
    "rank": 39,
    "english": "I don't understand",
    "spanish": "No entiendo",
    "category": "Communication",
    "kind": "phrase",
    "exampleEn": "Sorry, I don't understand.",
    "exampleEs": "Lo siento, no entiendo.",
    "family": "understanding",
    "morphology": "entiendo / entiendes / entiende",
    "note": "",
    "cefr": "A1",
    "usefulness": 92,
    "band": "Very common"
  },
  {
    "rank": 40,
    "english": "Can you repeat that?",
    "spanish": "¿Puede repetirlo?",
    "category": "Communication",
    "kind": "phrase",
    "exampleEn": "Can you repeat that, please?",
    "exampleEs": "¿Puede repetirlo, por favor?",
    "family": "communication repair",
    "morphology": "puede / repetir",
    "note": "A polite form; ¿Puedes repetirlo? is informal.",
    "cefr": "A1",
    "usefulness": 92,
    "band": "Very common"
  },
  {
    "rank": 41,
    "english": "I want...",
    "spanish": "Quiero...",
    "category": "Needs",
    "kind": "phrase",
    "exampleEn": "I want water.",
    "exampleEs": "Quiero agua.",
    "family": "wanting",
    "morphology": "quiero / quieres / quiere",
    "note": "Querer is irregular in the present tense.",
    "cefr": "A1",
    "usefulness": 91,
    "band": "Very common"
  },
  {
    "rank": 42,
    "english": "I need...",
    "spanish": "Necesito...",
    "category": "Needs",
    "kind": "phrase",
    "exampleEn": "I need help.",
    "exampleEs": "Necesito ayuda.",
    "family": "needs",
    "morphology": "necesito / necesitas / necesita",
    "note": "",
    "cefr": "A1",
    "usefulness": 91,
    "band": "Very common"
  },
  {
    "rank": 43,
    "english": "I have...",
    "spanish": "Tengo...",
    "category": "Needs",
    "kind": "phrase",
    "exampleEn": "I have a reservation.",
    "exampleEs": "Tengo una reserva.",
    "family": "having",
    "morphology": "tengo / tienes / tiene",
    "note": "Tener is irregular and also appears in age expressions.",
    "cefr": "A1",
    "usefulness": 91,
    "band": "Very common"
  },
  {
    "rank": 44,
    "english": "I am...",
    "spanish": "Soy / estoy...",
    "category": "Needs",
    "kind": "phrase",
    "exampleEn": "I am tired.",
    "exampleEs": "Estoy cansado.",
    "family": "being",
    "morphology": "soy / estoy",
    "note": "Use ser for identity/classification and estar for many states/locations.",
    "cefr": "A1",
    "usefulness": 90,
    "band": "Very common"
  },
  {
    "rank": 45,
    "english": "I like...",
    "spanish": "Me gusta...",
    "category": "Needs",
    "kind": "phrase",
    "exampleEn": "I like coffee.",
    "exampleEs": "Me gusta el café.",
    "family": "likes",
    "morphology": "me gusta / me gustan",
    "note": "Use gustan with plural things: me gustan los libros.",
    "cefr": "A1",
    "usefulness": 90,
    "band": "Very common"
  },
  {
    "rank": 46,
    "english": "I don't like...",
    "spanish": "No me gusta...",
    "category": "Needs",
    "kind": "phrase",
    "exampleEn": "I don't like tea.",
    "exampleEs": "No me gusta el té.",
    "family": "likes",
    "morphology": "no me gusta / no me gustan",
    "note": "",
    "cefr": "A1",
    "usefulness": 90,
    "band": "Very common"
  },
  {
    "rank": 47,
    "english": "I can...",
    "spanish": "Puedo...",
    "category": "Needs",
    "kind": "phrase",
    "exampleEn": "I can pay by card.",
    "exampleEs": "Puedo pagar con tarjeta.",
    "family": "ability",
    "morphology": "puedo / puedes / puede",
    "note": "Poder is irregular in the present tense.",
    "cefr": "A1",
    "usefulness": 89,
    "band": "Very common"
  },
  {
    "rank": 48,
    "english": "I can't...",
    "spanish": "No puedo...",
    "category": "Needs",
    "kind": "phrase",
    "exampleEn": "I can't understand.",
    "exampleEs": "No puedo entender.",
    "family": "ability",
    "morphology": "no puedo / no puedes",
    "note": "Put no directly before puedo.",
    "cefr": "A1",
    "usefulness": 89,
    "band": "Very common"
  },
  {
    "rank": 49,
    "english": "Go",
    "spanish": "Ir",
    "category": "Actions",
    "kind": "verb",
    "exampleEn": "I am going to the hotel.",
    "exampleEs": "Voy al hotel.",
    "family": "movement verbs",
    "morphology": "voy / vas / va / vamos / van",
    "note": "Ir is highly irregular.",
    "cefr": "A1",
    "usefulness": 89,
    "band": "Very common"
  },
  {
    "rank": 50,
    "english": "Come",
    "spanish": "Venir",
    "category": "Actions",
    "kind": "verb",
    "exampleEn": "Can you come here?",
    "exampleEs": "¿Puede venir aquí?",
    "family": "movement verbs",
    "morphology": "vengo / vienes / viene",
    "note": "Venir is irregular.",
    "cefr": "A1",
    "usefulness": 88,
    "band": "Very common"
  },
  {
    "rank": 51,
    "english": "Eat",
    "spanish": "Comer",
    "category": "Actions",
    "kind": "verb",
    "exampleEn": "I want to eat.",
    "exampleEs": "Quiero comer.",
    "family": "daily verbs",
    "morphology": "como / comes / come / comemos / comen",
    "note": "",
    "cefr": "A1",
    "usefulness": 88,
    "band": "Very common"
  },
  {
    "rank": 52,
    "english": "Drink",
    "spanish": "Beber",
    "category": "Actions",
    "kind": "verb",
    "exampleEn": "I want to drink water.",
    "exampleEs": "Quiero beber agua.",
    "family": "daily verbs",
    "morphology": "bebo / bebes / bebe / bebemos / beben",
    "note": "",
    "cefr": "A1",
    "usefulness": 88,
    "band": "Very common"
  },
  {
    "rank": 53,
    "english": "Sleep",
    "spanish": "Dormir",
    "category": "Actions",
    "kind": "verb",
    "exampleEn": "I need to sleep.",
    "exampleEs": "Necesito dormir.",
    "family": "daily verbs",
    "morphology": "duermo / duermes / duerme",
    "note": "Dormir has a stem change in much of the present tense.",
    "cefr": "A1",
    "usefulness": 87,
    "band": "Very common"
  },
  {
    "rank": 54,
    "english": "Work",
    "spanish": "Trabajar",
    "category": "Actions",
    "kind": "verb",
    "exampleEn": "I work here.",
    "exampleEs": "Trabajo aquí.",
    "family": "daily verbs",
    "morphology": "trabajo / trabajas / trabaja",
    "note": "",
    "cefr": "A1",
    "usefulness": 87,
    "band": "Very common"
  },
  {
    "rank": 55,
    "english": "Live",
    "spanish": "Vivir",
    "category": "Actions",
    "kind": "verb",
    "exampleEn": "I live in England.",
    "exampleEs": "Vivo en Inglaterra.",
    "family": "daily verbs",
    "morphology": "vivo / vives / vive",
    "note": "",
    "cefr": "A1",
    "usefulness": 87,
    "band": "Very common"
  },
  {
    "rank": 56,
    "english": "Know",
    "spanish": "Saber / conocer",
    "category": "Actions",
    "kind": "verb",
    "exampleEn": "I know the answer.",
    "exampleEs": "Sé la respuesta.",
    "family": "knowledge verbs",
    "morphology": "sé / sabes; conozco / conoces",
    "note": "Saber is for facts/how-to; conocer is for people, places and familiarity.",
    "cefr": "A1",
    "usefulness": 86,
    "band": "Very common"
  },
  {
    "rank": 57,
    "english": "Understand",
    "spanish": "Entender",
    "category": "Actions",
    "kind": "verb",
    "exampleEn": "I understand a little.",
    "exampleEs": "Entiendo un poco.",
    "family": "communication verbs",
    "morphology": "entiendo / entiendes / entiende",
    "note": "Entender has a stem change in much of the present tense.",
    "cefr": "A1",
    "usefulness": 86,
    "band": "Very common"
  },
  {
    "rank": 58,
    "english": "Speak",
    "spanish": "Hablar",
    "category": "Actions",
    "kind": "verb",
    "exampleEn": "I speak a little Spanish.",
    "exampleEs": "Hablo un poco de español.",
    "family": "communication verbs",
    "morphology": "hablo / hablas / habla",
    "note": "",
    "cefr": "A1",
    "usefulness": 86,
    "band": "Very common"
  },
  {
    "rank": 59,
    "english": "Buy",
    "spanish": "Comprar",
    "category": "Actions",
    "kind": "verb",
    "exampleEn": "I want to buy this.",
    "exampleEs": "Quiero comprar esto.",
    "family": "shopping verbs",
    "morphology": "compro / compras / compra",
    "note": "",
    "cefr": "A1",
    "usefulness": 85,
    "band": "Very common"
  },
  {
    "rank": 60,
    "english": "Pay",
    "spanish": "Pagar",
    "category": "Actions",
    "kind": "verb",
    "exampleEn": "Can I pay by card?",
    "exampleEs": "¿Puedo pagar con tarjeta?",
    "family": "shopping verbs",
    "morphology": "pago / pagas / paga",
    "note": "",
    "cefr": "A1",
    "usefulness": 85,
    "band": "Very common"
  },
  {
    "rank": 61,
    "english": "Today",
    "spanish": "Hoy",
    "category": "Time",
    "kind": "word",
    "exampleEn": "I work today.",
    "exampleEs": "Trabajo hoy.",
    "family": "day words",
    "morphology": "",
    "note": "",
    "cefr": "A1",
    "usefulness": 84,
    "band": "Common"
  },
  {
    "rank": 62,
    "english": "Tomorrow",
    "spanish": "Mañana",
    "category": "Time",
    "kind": "word",
    "exampleEn": "See you tomorrow.",
    "exampleEs": "Hasta mañana.",
    "family": "day words",
    "morphology": "",
    "note": "Mañana can mean tomorrow or morning; context tells you which.",
    "cefr": "A1",
    "usefulness": 84,
    "band": "Common"
  },
  {
    "rank": 63,
    "english": "Yesterday",
    "spanish": "Ayer",
    "category": "Time",
    "kind": "word",
    "exampleEn": "I arrived yesterday.",
    "exampleEs": "Llegué ayer.",
    "family": "day words",
    "morphology": "",
    "note": "",
    "cefr": "A1",
    "usefulness": 84,
    "band": "Common"
  },
  {
    "rank": 64,
    "english": "Now",
    "spanish": "Ahora",
    "category": "Time",
    "kind": "word",
    "exampleEn": "I need help now.",
    "exampleEs": "Necesito ayuda ahora.",
    "family": "time words",
    "morphology": "",
    "note": "",
    "cefr": "A1",
    "usefulness": 84,
    "band": "Common"
  },
  {
    "rank": 65,
    "english": "Later",
    "spanish": "Más tarde",
    "category": "Time",
    "kind": "phrase",
    "exampleEn": "See you later.",
    "exampleEs": "Hasta más tarde.",
    "family": "time words",
    "morphology": "",
    "note": "",
    "cefr": "A1",
    "usefulness": 84,
    "band": "Common"
  },
  {
    "rank": 66,
    "english": "Morning",
    "spanish": "Mañana",
    "category": "Time",
    "kind": "word",
    "exampleEn": "In the morning.",
    "exampleEs": "Por la mañana.",
    "family": "parts of day",
    "morphology": "",
    "note": "Mañana can also mean tomorrow.",
    "cefr": "A1",
    "usefulness": 83,
    "band": "Common"
  },
  {
    "rank": 67,
    "english": "Afternoon",
    "spanish": "Tarde",
    "category": "Time",
    "kind": "word",
    "exampleEn": "In the afternoon.",
    "exampleEs": "Por la tarde.",
    "family": "parts of day",
    "morphology": "",
    "note": "",
    "cefr": "A1",
    "usefulness": 83,
    "band": "Common"
  },
  {
    "rank": 68,
    "english": "Evening",
    "spanish": "Tarde / noche",
    "category": "Time",
    "kind": "word",
    "exampleEn": "This evening.",
    "exampleEs": "Esta tarde / esta noche.",
    "family": "parts of day",
    "morphology": "",
    "note": "The boundary between tarde and noche varies with context and local habits.",
    "cefr": "A1",
    "usefulness": 83,
    "band": "Common"
  },
  {
    "rank": 69,
    "english": "Night",
    "spanish": "Noche",
    "category": "Time",
    "kind": "word",
    "exampleEn": "At night.",
    "exampleEs": "Por la noche.",
    "family": "parts of day",
    "morphology": "",
    "note": "",
    "cefr": "A1",
    "usefulness": 83,
    "band": "Common"
  },
  {
    "rank": 70,
    "english": "Time",
    "spanish": "Tiempo",
    "category": "Time",
    "kind": "word",
    "exampleEn": "I don't have time.",
    "exampleEs": "No tengo tiempo.",
    "family": "time nouns",
    "morphology": "tiempo / tiempos",
    "note": "For clock time, Spanish often uses hora instead.",
    "cefr": "A1",
    "usefulness": 83,
    "band": "Common"
  },
  {
    "rank": 71,
    "english": "Hour",
    "spanish": "Hora",
    "category": "Time",
    "kind": "word",
    "exampleEn": "One hour.",
    "exampleEs": "Una hora.",
    "family": "time nouns",
    "morphology": "hora / horas",
    "note": "",
    "cefr": "A1",
    "usefulness": 82,
    "band": "Common"
  },
  {
    "rank": 72,
    "english": "Minute",
    "spanish": "Minuto",
    "category": "Time",
    "kind": "word",
    "exampleEn": "Five minutes.",
    "exampleEs": "Cinco minutos.",
    "family": "time nouns",
    "morphology": "minuto / minutos",
    "note": "",
    "cefr": "A1",
    "usefulness": 82,
    "band": "Common"
  },
  {
    "rank": 73,
    "english": "Here",
    "spanish": "Aquí",
    "category": "Places",
    "kind": "word",
    "exampleEn": "I am here.",
    "exampleEs": "Estoy aquí.",
    "family": "location words",
    "morphology": "aquí",
    "note": "",
    "cefr": "A1",
    "usefulness": 82,
    "band": "Common"
  },
  {
    "rank": 74,
    "english": "There",
    "spanish": "Allí / ahí",
    "category": "Places",
    "kind": "word",
    "exampleEn": "The hotel is there.",
    "exampleEs": "El hotel está allí.",
    "family": "location words",
    "morphology": "aquí / ahí / allí",
    "note": "Spanish often distinguishes there-near-you (ahí) from farther there (allí).",
    "cefr": "A1",
    "usefulness": 82,
    "band": "Common"
  },
  {
    "rank": 75,
    "english": "Left",
    "spanish": "Izquierda",
    "category": "Places",
    "kind": "word",
    "exampleEn": "Turn left.",
    "exampleEs": "Gire a la izquierda.",
    "family": "directions",
    "morphology": "izquierda",
    "note": "",
    "cefr": "A1",
    "usefulness": 82,
    "band": "Common"
  },
  {
    "rank": 76,
    "english": "Right",
    "spanish": "Derecha",
    "category": "Places",
    "kind": "word",
    "exampleEn": "Turn right.",
    "exampleEs": "Gire a la derecha.",
    "family": "directions",
    "morphology": "derecha",
    "note": "",
    "cefr": "A1",
    "usefulness": 81,
    "band": "Common"
  },
  {
    "rank": 77,
    "english": "Straight ahead",
    "spanish": "Todo recto",
    "category": "Places",
    "kind": "phrase",
    "exampleEn": "Go straight ahead.",
    "exampleEs": "Siga todo recto.",
    "family": "directions",
    "morphology": "",
    "note": "Common in directions, especially in Spain.",
    "cefr": "A1",
    "usefulness": 81,
    "band": "Common"
  },
  {
    "rank": 78,
    "english": "Near",
    "spanish": "Cerca",
    "category": "Places",
    "kind": "word",
    "exampleEn": "The hotel is near.",
    "exampleEs": "El hotel está cerca.",
    "family": "distance words",
    "morphology": "cerca de",
    "note": "Use cerca de before a noun: cerca del hotel.",
    "cefr": "A1",
    "usefulness": 81,
    "band": "Common"
  },
  {
    "rank": 79,
    "english": "Far",
    "spanish": "Lejos",
    "category": "Places",
    "kind": "word",
    "exampleEn": "Is it far?",
    "exampleEs": "¿Está lejos?",
    "family": "distance words",
    "morphology": "lejos de",
    "note": "",
    "cefr": "A1",
    "usefulness": 81,
    "band": "Common"
  },
  {
    "rank": 80,
    "english": "Home",
    "spanish": "Casa",
    "category": "Places",
    "kind": "word",
    "exampleEn": "I am at home.",
    "exampleEs": "Estoy en casa.",
    "family": "places",
    "morphology": "casa / casas",
    "note": "Spanish often says en casa without an article for 'at home'.",
    "cefr": "A1",
    "usefulness": 81,
    "band": "Common"
  },
  {
    "rank": 81,
    "english": "Hotel",
    "spanish": "Hotel",
    "category": "Places",
    "kind": "word",
    "exampleEn": "Where is the hotel?",
    "exampleEs": "¿Dónde está el hotel?",
    "family": "places",
    "morphology": "hotel / hoteles",
    "note": "A very transparent English-Spanish cognate.",
    "cefr": "A1",
    "usefulness": 80,
    "band": "Common"
  },
  {
    "rank": 82,
    "english": "Bathroom / toilet",
    "spanish": "Baño",
    "category": "Places",
    "kind": "word",
    "exampleEn": "Where is the bathroom?",
    "exampleEs": "¿Dónde está el baño?",
    "family": "places",
    "morphology": "baño / baños",
    "note": "",
    "cefr": "A1",
    "usefulness": 80,
    "band": "Common"
  },
  {
    "rank": 83,
    "english": "Restaurant",
    "spanish": "Restaurante",
    "category": "Places",
    "kind": "word",
    "exampleEn": "The restaurant is near.",
    "exampleEs": "El restaurante está cerca.",
    "family": "places",
    "morphology": "restaurante / restaurantes",
    "note": "A useful cognate with a small spelling change.",
    "cefr": "A1",
    "usefulness": 80,
    "band": "Common"
  },
  {
    "rank": 84,
    "english": "Shop / store",
    "spanish": "Tienda",
    "category": "Places",
    "kind": "word",
    "exampleEn": "Where is the shop?",
    "exampleEs": "¿Dónde está la tienda?",
    "family": "places",
    "morphology": "tienda / tiendas",
    "note": "",
    "cefr": "A1",
    "usefulness": 80,
    "band": "Common"
  },
  {
    "rank": 85,
    "english": "Station",
    "spanish": "Estación",
    "category": "Places",
    "kind": "word",
    "exampleEn": "Where is the station?",
    "exampleEs": "¿Dónde está la estación?",
    "family": "places",
    "morphology": "estación / estaciones",
    "note": "Notice the familiar -tion → -ción relationship in station/estación.",
    "cefr": "A1",
    "usefulness": 80,
    "band": "Common"
  },
  {
    "rank": 86,
    "english": "Water",
    "spanish": "Agua",
    "category": "Food & drink",
    "kind": "word",
    "exampleEn": "Water, please.",
    "exampleEs": "Agua, por favor.",
    "family": "drinks",
    "morphology": "agua",
    "note": "Agua is feminine, although singular often uses el: el agua fría.",
    "cefr": "A1",
    "usefulness": 79,
    "band": "Common"
  },
  {
    "rank": 87,
    "english": "Food",
    "spanish": "Comida",
    "category": "Food & drink",
    "kind": "word",
    "exampleEn": "The food is good.",
    "exampleEs": "La comida está buena.",
    "family": "food",
    "morphology": "comida / comidas",
    "note": "Comida can also mean the main midday meal in some regions.",
    "cefr": "A1",
    "usefulness": 79,
    "band": "Common"
  },
  {
    "rank": 88,
    "english": "Coffee",
    "spanish": "Café",
    "category": "Food & drink",
    "kind": "word",
    "exampleEn": "A coffee, please.",
    "exampleEs": "Un café, por favor.",
    "family": "drinks",
    "morphology": "café / cafés",
    "note": "",
    "cefr": "A1",
    "usefulness": 79,
    "band": "Common"
  },
  {
    "rank": 89,
    "english": "Tea",
    "spanish": "Té",
    "category": "Food & drink",
    "kind": "word",
    "exampleEn": "Tea, please.",
    "exampleEs": "Té, por favor.",
    "family": "drinks",
    "morphology": "té / tés",
    "note": "The accent distinguishes té (tea) from te (you, object pronoun).",
    "cefr": "A1",
    "usefulness": 79,
    "band": "Common"
  },
  {
    "rank": 90,
    "english": "Bread",
    "spanish": "Pan",
    "category": "Food & drink",
    "kind": "word",
    "exampleEn": "Bread, please.",
    "exampleEs": "Pan, por favor.",
    "family": "food",
    "morphology": "pan / panes",
    "note": "",
    "cefr": "A1",
    "usefulness": 79,
    "band": "Common"
  },
  {
    "rank": 91,
    "english": "Breakfast",
    "spanish": "Desayuno",
    "category": "Food & drink",
    "kind": "word",
    "exampleEn": "Breakfast is at eight.",
    "exampleEs": "El desayuno es a las ocho.",
    "family": "meals",
    "morphology": "desayuno / desayunos",
    "note": "",
    "cefr": "A1",
    "usefulness": 78,
    "band": "Common"
  },
  {
    "rank": 92,
    "english": "Lunch",
    "spanish": "Almuerzo / comida",
    "category": "Food & drink",
    "kind": "word",
    "exampleEn": "Lunch is at one.",
    "exampleEs": "El almuerzo es a la una.",
    "family": "meals",
    "morphology": "almuerzo / comida",
    "note": "Meal names and timing vary a lot by country.",
    "cefr": "A1",
    "usefulness": 78,
    "band": "Common"
  },
  {
    "rank": 93,
    "english": "Dinner",
    "spanish": "Cena",
    "category": "Food & drink",
    "kind": "word",
    "exampleEn": "Dinner is at nine.",
    "exampleEs": "La cena es a las nueve.",
    "family": "meals",
    "morphology": "cena / cenas",
    "note": "",
    "cefr": "A1",
    "usefulness": 78,
    "band": "Common"
  },
  {
    "rank": 94,
    "english": "Help!",
    "spanish": "¡Ayuda!",
    "category": "Safety",
    "kind": "phrase",
    "exampleEn": "Help! I am lost.",
    "exampleEs": "¡Ayuda! Estoy perdido.",
    "family": "emergency language",
    "morphology": "ayuda / ayudar",
    "note": "",
    "cefr": "A1",
    "usefulness": 78,
    "band": "Common"
  },
  {
    "rank": 95,
    "english": "Doctor",
    "spanish": "Médico / médica",
    "category": "Safety",
    "kind": "word",
    "exampleEn": "I need a doctor.",
    "exampleEs": "Necesito un médico.",
    "family": "people",
    "morphology": "médico / médica",
    "note": "",
    "cefr": "A1",
    "usefulness": 78,
    "band": "Common"
  },
  {
    "rank": 96,
    "english": "Hospital",
    "spanish": "Hospital",
    "category": "Safety",
    "kind": "word",
    "exampleEn": "Where is the hospital?",
    "exampleEs": "¿Dónde está el hospital?",
    "family": "places",
    "morphology": "hospital / hospitales",
    "note": "A transparent cognate.",
    "cefr": "A1",
    "usefulness": 77,
    "band": "Common"
  },
  {
    "rank": 97,
    "english": "Police",
    "spanish": "Policía",
    "category": "Safety",
    "kind": "word",
    "exampleEn": "Call the police.",
    "exampleEs": "Llame a la policía.",
    "family": "safety",
    "morphology": "policía",
    "note": "Policía can refer to the police force or an officer depending on context.",
    "cefr": "A1",
    "usefulness": 77,
    "band": "Common"
  },
  {
    "rank": 98,
    "english": "Money",
    "spanish": "Dinero",
    "category": "Money",
    "kind": "word",
    "exampleEn": "I need money.",
    "exampleEs": "Necesito dinero.",
    "family": "money",
    "morphology": "",
    "note": "",
    "cefr": "A1",
    "usefulness": 77,
    "band": "Common"
  },
  {
    "rank": 99,
    "english": "Card",
    "spanish": "Tarjeta",
    "category": "Money",
    "kind": "word",
    "exampleEn": "Can I pay by card?",
    "exampleEs": "¿Puedo pagar con tarjeta?",
    "family": "payments",
    "morphology": "tarjeta / tarjetas",
    "note": "",
    "cefr": "A1",
    "usefulness": 77,
    "band": "Common"
  },
  {
    "rank": 100,
    "english": "Cash",
    "spanish": "Efectivo",
    "category": "Money",
    "kind": "word",
    "exampleEn": "Do you accept cash?",
    "exampleEs": "¿Acepta efectivo?",
    "family": "payments",
    "morphology": "efectivo",
    "note": "Efectivo also has other meanings in other contexts; here it means cash.",
    "cefr": "A2",
    "usefulness": 77,
    "band": "Common"
  }
];
