window.LANGUAGE_DNA_PATTERN_DICTIONARIES={
  "tion-cion": {
    "id": "tion-cion",
    "title": "-tion → -ción",
    "explanation": "Many English nouns ending in -tion have a closely related Spanish form ending in -ción.",
    "listenLanguage": "es-ES",
    "words": [
      [
        "abbreviation",
        "abreviación"
      ],
      [
        "acceleration",
        "aceleración"
      ],
      [
        "accusation",
        "acusación"
      ],
      [
        "acquisition",
        "adquisición"
      ],
      [
        "action",
        "acción"
      ],
      [
        "activation",
        "activación"
      ],
      [
        "adaptation",
        "adaptación"
      ],
      [
        "addition",
        "adición"
      ],
      [
        "administration",
        "administración"
      ],
      [
        "admiration",
        "admiración"
      ],
      [
        "adoption",
        "adopción"
      ],
      [
        "affirmation",
        "afirmación"
      ],
      [
        "agitation",
        "agitación"
      ],
      [
        "alteration",
        "alteración"
      ],
      [
        "ambition",
        "ambición"
      ],
      [
        "animation",
        "animación"
      ],
      [
        "anticipation",
        "anticipación"
      ],
      [
        "application",
        "aplicación"
      ],
      [
        "appreciation",
        "apreciación"
      ],
      [
        "articulation",
        "articulación"
      ],
      [
        "assimilation",
        "asimilación"
      ],
      [
        "association",
        "asociación"
      ],
      [
        "attention",
        "atención"
      ],
      [
        "attraction",
        "atracción"
      ],
      [
        "authentication",
        "autenticación"
      ],
      [
        "authorization",
        "autorización"
      ],
      [
        "automation",
        "automatización"
      ],
      [
        "cancellation",
        "cancelación"
      ],
      [
        "celebration",
        "celebración"
      ],
      [
        "circulation",
        "circulación"
      ],
      [
        "citation",
        "citación"
      ],
      [
        "civilization",
        "civilización"
      ],
      [
        "classification",
        "clasificación"
      ],
      [
        "collaboration",
        "colaboración"
      ],
      [
        "collection",
        "colección"
      ],
      [
        "combination",
        "combinación"
      ],
      [
        "communication",
        "comunicación"
      ],
      [
        "competition",
        "competición"
      ],
      [
        "complication",
        "complicación"
      ],
      [
        "composition",
        "composición"
      ],
      [
        "concentration",
        "concentración"
      ],
      [
        "conception",
        "concepción"
      ],
      [
        "condition",
        "condición"
      ],
      [
        "configuration",
        "configuración"
      ],
      [
        "confirmation",
        "confirmación"
      ],
      [
        "confrontation",
        "confrontación"
      ],
      [
        "congregation",
        "congregación"
      ],
      [
        "conjugation",
        "conjugación"
      ],
      [
        "conservation",
        "conservación"
      ],
      [
        "consideration",
        "consideración"
      ],
      [
        "constellation",
        "constelación"
      ],
      [
        "construction",
        "construcción"
      ],
      [
        "contamination",
        "contaminación"
      ],
      [
        "continuation",
        "continuación"
      ],
      [
        "contribution",
        "contribución"
      ],
      [
        "conversation",
        "conversación"
      ],
      [
        "cooperation",
        "cooperación"
      ],
      [
        "coordination",
        "coordinación"
      ],
      [
        "creation",
        "creación"
      ],
      [
        "cultivation",
        "cultivación"
      ],
      [
        "declaration",
        "declaración"
      ],
      [
        "decoration",
        "decoración"
      ],
      [
        "dedication",
        "dedicación"
      ],
      [
        "definition",
        "definición"
      ],
      [
        "delegation",
        "delegación"
      ],
      [
        "demonstration",
        "demostración"
      ],
      [
        "deportation",
        "deportación"
      ],
      [
        "description",
        "descripción"
      ],
      [
        "determination",
        "determinación"
      ],
      [
        "deviation",
        "desviación"
      ],
      [
        "differentiation",
        "diferenciación"
      ],
      [
        "direction",
        "dirección"
      ],
      [
        "discrimination",
        "discriminación"
      ],
      [
        "distribution",
        "distribución"
      ],
      [
        "documentation",
        "documentación"
      ],
      [
        "donation",
        "donación"
      ],
      [
        "duration",
        "duración"
      ],
      [
        "edition",
        "edición"
      ],
      [
        "education",
        "educación"
      ],
      [
        "election",
        "elección"
      ],
      [
        "elimination",
        "eliminación"
      ],
      [
        "emotion",
        "emoción"
      ],
      [
        "evacuation",
        "evacuación"
      ],
      [
        "evaluation",
        "evaluación"
      ],
      [
        "evolution",
        "evolución"
      ],
      [
        "excavation",
        "excavación"
      ],
      [
        "exception",
        "excepción"
      ],
      [
        "exclamation",
        "exclamación"
      ],
      [
        "exhibition",
        "exhibición"
      ],
      [
        "explanation",
        "explicación"
      ],
      [
        "exploration",
        "exploración"
      ],
      [
        "expression",
        "expresión"
      ],
      [
        "fabrication",
        "fabricación"
      ],
      [
        "federation",
        "federación"
      ],
      [
        "formation",
        "formación"
      ],
      [
        "foundation",
        "fundación"
      ],
      [
        "fragmentation",
        "fragmentación"
      ],
      [
        "frustration",
        "frustración"
      ],
      [
        "function",
        "función"
      ],
      [
        "generation",
        "generación"
      ],
      [
        "globalization",
        "globalización"
      ],
      [
        "graduation",
        "graduación"
      ],
      [
        "identification",
        "identificación"
      ],
      [
        "illumination",
        "iluminación"
      ],
      [
        "illustration",
        "ilustración"
      ],
      [
        "imagination",
        "imaginación"
      ],
      [
        "imitation",
        "imitación"
      ],
      [
        "immigration",
        "inmigración"
      ],
      [
        "implementation",
        "implementación"
      ],
      [
        "inclination",
        "inclinación"
      ],
      [
        "indication",
        "indicación"
      ],
      [
        "inflation",
        "inflación"
      ],
      [
        "information",
        "información"
      ],
      [
        "inhalation",
        "inhalación"
      ],
      [
        "innovation",
        "innovación"
      ],
      [
        "inspection",
        "inspección"
      ],
      [
        "installation",
        "instalación"
      ],
      [
        "institution",
        "institución"
      ],
      [
        "integration",
        "integración"
      ],
      [
        "interpretation",
        "interpretación"
      ],
      [
        "introduction",
        "introducción"
      ],
      [
        "invention",
        "invención"
      ],
      [
        "investigation",
        "investigación"
      ],
      [
        "invitation",
        "invitación"
      ],
      [
        "justification",
        "justificación"
      ],
      [
        "legislation",
        "legislación"
      ],
      [
        "liberation",
        "liberación"
      ],
      [
        "limitation",
        "limitación"
      ],
      [
        "localization",
        "localización"
      ],
      [
        "manipulation",
        "manipulación"
      ],
      [
        "meditation",
        "meditación"
      ],
      [
        "migration",
        "migración"
      ],
      [
        "modification",
        "modificación"
      ],
      [
        "motivation",
        "motivación"
      ],
      [
        "mutation",
        "mutación"
      ],
      [
        "navigation",
        "navegación"
      ],
      [
        "negotiation",
        "negociación"
      ],
      [
        "nomination",
        "nominación"
      ],
      [
        "notification",
        "notificación"
      ],
      [
        "observation",
        "observación"
      ],
      [
        "occupation",
        "ocupación"
      ],
      [
        "operation",
        "operación"
      ],
      [
        "optimization",
        "optimización"
      ],
      [
        "organization",
        "organización"
      ],
      [
        "orientation",
        "orientación"
      ],
      [
        "participation",
        "participación"
      ],
      [
        "perforation",
        "perforación"
      ],
      [
        "plantation",
        "plantación"
      ],
      [
        "population",
        "población"
      ],
      [
        "position",
        "posición"
      ],
      [
        "prediction",
        "predicción"
      ],
      [
        "preparation",
        "preparación"
      ],
      [
        "presentation",
        "presentación"
      ],
      [
        "preservation",
        "preservación"
      ],
      [
        "prevention",
        "prevención"
      ],
      [
        "privatization",
        "privatización"
      ],
      [
        "proclamation",
        "proclamación"
      ],
      [
        "production",
        "producción"
      ],
      [
        "projection",
        "proyección"
      ],
      [
        "pronunciation",
        "pronunciación"
      ],
      [
        "proportion",
        "proporción"
      ],
      [
        "protection",
        "protección"
      ],
      [
        "publication",
        "publicación"
      ],
      [
        "punctuation",
        "puntuación"
      ],
      [
        "qualification",
        "cualificación"
      ],
      [
        "radiation",
        "radiación"
      ],
      [
        "reaction",
        "reacción"
      ],
      [
        "recommendation",
        "recomendación"
      ],
      [
        "reconciliation",
        "reconciliación"
      ],
      [
        "recreation",
        "recreación"
      ],
      [
        "reduction",
        "reducción"
      ],
      [
        "relation",
        "relación"
      ],
      [
        "relaxation",
        "relajación"
      ],
      [
        "repetition",
        "repetición"
      ],
      [
        "representation",
        "representación"
      ],
      [
        "reproduction",
        "reproducción"
      ],
      [
        "reservation",
        "reservación"
      ],
      [
        "resolution",
        "resolución"
      ],
      [
        "restoration",
        "restauración"
      ],
      [
        "rotation",
        "rotación"
      ],
      [
        "satisfaction",
        "satisfacción"
      ],
      [
        "section",
        "sección"
      ],
      [
        "segmentation",
        "segmentación"
      ],
      [
        "selection",
        "selección"
      ],
      [
        "separation",
        "separación"
      ],
      [
        "simulation",
        "simulación"
      ],
      [
        "situation",
        "situación"
      ],
      [
        "solution",
        "solución"
      ],
      [
        "specialization",
        "especialización"
      ],
      [
        "specification",
        "especificación"
      ],
      [
        "station",
        "estación"
      ],
      [
        "substitution",
        "sustitución"
      ],
      [
        "termination",
        "terminación"
      ],
      [
        "transformation",
        "transformación"
      ],
      [
        "translation",
        "traducción"
      ],
      [
        "transportation",
        "transportación"
      ],
      [
        "unification",
        "unificación"
      ],
      [
        "utilization",
        "utilización"
      ],
      [
        "vaccination",
        "vacunación"
      ],
      [
        "validation",
        "validación"
      ],
      [
        "variation",
        "variación"
      ],
      [
        "ventilation",
        "ventilación"
      ],
      [
        "verification",
        "verificación"
      ],
      [
        "vibration",
        "vibración"
      ],
      [
        "visualization",
        "visualización"
      ]
    ]
  }
};
