window.LANGUAGE_DNA_PATTERN_DICTIONARIES={
  "tion-cion": {
    "id": "tion-cion",
    "title": "-tion → -ción",
    "explanation": "Many English nouns ending in -tion have a closely related Spanish form ending in -ción.",
    "listenLanguage": "es-ES",
    "words": [
      [
        "abbreviation",
        "abreviación"
      ],
      [
        "acceleration",
        "aceleración"
      ],
      [
        "accusation",
        "acusación"
      ],
      [
        "acquisition",
        "adquisición"
      ],
      [
        "action",
        "acción"
      ],
      [
        "activation",
        "activación"
      ],
      [
        "adaptation",
        "adaptación"
      ],
      [
        "addition",
        "adición"
      ],
      [
        "administration",
        "administración"
      ],
      [
        "admiration",
        "admiración"
      ],
      [
        "adoption",
        "adopción"
      ],
      [
        "affirmation",
        "afirmación"
      ],
      [
        "agitation",
        "agitación"
      ],
      [
        "alteration",
        "alteración"
      ],
      [
        "ambition",
        "ambición"
      ],
      [
        "animation",
        "animación"
      ],
      [
        "anticipation",
        "anticipación"
      ],
      [
        "application",
        "aplicación"
      ],
      [
        "appreciation",
        "apreciación"
      ],
      [
        "articulation",
        "articulación"
      ],
      [
        "assimilation",
        "asimilación"
      ],
      [
        "association",
        "asociación"
      ],
      [
        "attention",
        "atención"
      ],
      [
        "attraction",
        "atracción"
      ],
      [
        "authentication",
        "autenticación"
      ],
      [
        "authorization",
        "autorización"
      ],
      [
        "automation",
        "automatización"
      ],
      [
        "cancellation",
        "cancelación"
      ],
      [
        "celebration",
        "celebración"
      ],
      [
        "circulation",
        "circulación"
      ],
      [
        "citation",
        "citación"
      ],
      [
        "civilization",
        "civilización"
      ],
      [
        "classification",
        "clasificación"
      ],
      [
        "collaboration",
        "colaboración"
      ],
      [
        "collection",
        "colección"
      ],
      [
        "combination",
        "combinación"
      ],
      [
        "communication",
        "comunicación"
      ],
      [
        "competition",
        "competición"
      ],
      [
        "complication",
        "complicación"
      ],
      [
        "composition",
        "composición"
      ],
      [
        "concentration",
        "concentración"
      ],
      [
        "conception",
        "concepción"
      ],
      [
        "condition",
        "condición"
      ],
      [
        "configuration",
        "configuración"
      ],
      [
        "confirmation",
        "confirmación"
      ],
      [
        "confrontation",
        "confrontación"
      ],
      [
        "congregation",
        "congregación"
      ],
      [
        "conjugation",
        "conjugación"
      ],
      [
        "conservation",
        "conservación"
      ],
      [
        "consideration",
        "consideración"
      ],
      [
        "constellation",
        "constelación"
      ],
      [
        "construction",
        "construcción"
      ],
      [
        "contamination",
        "contaminación"
      ],
      [
        "continuation",
        "continuación"
      ],
      [
        "contribution",
        "contribución"
      ],
      [
        "conversation",
        "conversación"
      ],
      [
        "cooperation",
        "cooperación"
      ],
      [
        "coordination",
        "coordinación"
      ],
      [
        "creation",
        "creación"
      ],
      [
        "cultivation",
        "cultivación"
      ],
      [
        "declaration",
        "declaración"
      ],
      [
        "decoration",
        "decoración"
      ],
      [
        "dedication",
        "dedicación"
      ],
      [
        "definition",
        "definición"
      ],
      [
        "delegation",
        "delegación"
      ],
      [
        "demonstration",
        "demostración"
      ],
      [
        "deportation",
        "deportación"
      ],
      [
        "description",
        "descripción"
      ],
      [
        "determination",
        "determinación"
      ],
      [
        "deviation",
        "desviación"
      ],
      [
        "differentiation",
        "diferenciación"
      ],
      [
        "direction",
        "dirección"
      ],
      [
        "discrimination",
        "discriminación"
      ],
      [
        "distribution",
        "distribución"
      ],
      [
        "documentation",
        "documentación"
      ],
      [
        "donation",
        "donación"
      ],
      [
        "duration",
        "duración"
      ],
      [
        "edition",
        "edición"
      ],
      [
        "education",
        "educación"
      ],
      [
        "election",
        "elección"
      ],
      [
        "elimination",
        "eliminación"
      ],
      [
        "emotion",
        "emoción"
      ],
      [
        "evacuation",
        "evacuación"
      ],
      [
        "evaluation",
        "evaluación"
      ],
      [
        "evolution",
        "evolución"
      ],
      [
        "excavation",
        "excavación"
      ],
      [
        "exception",
        "excepción"
      ],
      [
        "exclamation",
        "exclamación"
      ],
      [
        "exhibition",
        "exhibición"
      ],
      [
        "explanation",
        "explicación"
      ],
      [
        "exploration",
        "exploración"
      ],
      [
        "expression",
        "expresión"
      ],
      [
        "fabrication",
        "fabricación"
      ],
      [
        "federation",
        "federación"
      ],
      [
        "formation",
        "formación"
      ],
      [
        "foundation",
        "fundación"
      ],
      [
        "fragmentation",
        "fragmentación"
      ],
      [
        "frustration",
        "frustración"
      ],
      [
        "function",
        "función"
      ],
      [
        "generation",
        "generación"
      ],
      [
        "globalization",
        "globalización"
      ],
      [
        "graduation",
        "graduación"
      ],
      [
        "identification",
        "identificación"
      ],
      [
        "illumination",
        "iluminación"
      ],
      [
        "illustration",
        "ilustración"
      ],
      [
        "imagination",
        "imaginación"
      ],
      [
        "imitation",
        "imitación"
      ],
      [
        "immigration",
        "inmigración"
      ],
      [
        "implementation",
        "implementación"
      ],
      [
        "inclination",
        "inclinación"
      ],
      [
        "indication",
        "indicación"
      ],
      [
        "inflation",
        "inflación"
      ],
      [
        "information",
        "información"
      ],
      [
        "inhalation",
        "inhalación"
      ],
      [
        "innovation",
        "innovación"
      ],
      [
        "inspection",
        "inspección"
      ],
      [
        "installation",
        "instalación"
      ],
      [
        "institution",
        "institución"
      ],
      [
        "integration",
        "integración"
      ],
      [
        "interpretation",
        "interpretación"
      ],
      [
        "introduction",
        "introducción"
      ],
      [
        "invention",
        "invención"
      ],
      [
        "investigation",
        "investigación"
      ],
      [
        "invitation",
        "invitación"
      ],
      [
        "justification",
        "justificación"
      ],
      [
        "legislation",
        "legislación"
      ],
      [
        "liberation",
        "liberación"
      ],
      [
        "limitation",
        "limitación"
      ],
      [
        "localization",
        "localización"
      ],
      [
        "manipulation",
        "manipulación"
      ],
      [
        "meditation",
        "meditación"
      ],
      [
        "migration",
        "migración"
      ],
      [
        "modification",
        "modificación"
      ],
      [
        "motivation",
        "motivación"
      ],
      [
        "mutation",
        "mutación"
      ],
      [
        "navigation",
        "navegación"
      ],
      [
        "negotiation",
        "negociación"
      ],
      [
        "nomination",
        "nominación"
      ],
      [
        "notification",
        "notificación"
      ],
      [
        "observation",
        "observación"
      ],
      [
        "occupation",
        "ocupación"
      ],
      [
        "operation",
        "operación"
      ],
      [
        "optimization",
        "optimización"
      ],
      [
        "organization",
        "organización"
      ],
      [
        "orientation",
        "orientación"
      ],
      [
        "participation",
        "participación"
      ],
      [
        "perforation",
        "perforación"
      ],
      [
        "plantation",
        "plantación"
      ],
      [
        "population",
        "población"
      ],
      [
        "position",
        "posición"
      ],
      [
        "prediction",
        "predicción"
      ],
      [
        "preparation",
        "preparación"
      ],
      [
        "presentation",
        "presentación"
      ],
      [
        "preservation",
        "preservación"
      ],
      [
        "prevention",
        "prevención"
      ],
      [
        "privatization",
        "privatización"
      ],
      [
        "proclamation",
        "proclamación"
      ],
      [
        "production",
        "producción"
      ],
      [
        "projection",
        "proyección"
      ],
      [
        "pronunciation",
        "pronunciación"
      ],
      [
        "proportion",
        "proporción"
      ],
      [
        "protection",
        "protección"
      ],
      [
        "publication",
        "publicación"
      ],
      [
        "punctuation",
        "puntuación"
      ],
      [
        "qualification",
        "cualificación"
      ],
      [
        "radiation",
        "radiación"
      ],
      [
        "reaction",
        "reacción"
      ],
      [
        "recommendation",
        "recomendación"
      ],
      [
        "reconciliation",
        "reconciliación"
      ],
      [
        "recreation",
        "recreación"
      ],
      [
        "reduction",
        "reducción"
      ],
      [
        "relation",
        "relación"
      ],
      [
        "relaxation",
        "relajación"
      ],
      [
        "repetition",
        "repetición"
      ],
      [
        "representation",
        "representación"
      ],
      [
        "reproduction",
        "reproducción"
      ],
      [
        "reservation",
        "reservación"
      ],
      [
        "resolution",
        "resolución"
      ],
      [
        "restoration",
        "restauración"
      ],
      [
        "rotation",
        "rotación"
      ],
      [
        "satisfaction",
        "satisfacción"
      ],
      [
        "section",
        "sección"
      ],
      [
        "segmentation",
        "segmentación"
      ],
      [
        "selection",
        "selección"
      ],
      [
        "separation",
        "separación"
      ],
      [
        "simulation",
        "simulación"
      ],
      [
        "situation",
        "situación"
      ],
      [
        "solution",
        "solución"
      ],
      [
        "specialization",
        "especialización"
      ],
      [
        "specification",
        "especificación"
      ],
      [
        "station",
        "estación"
      ],
      [
        "substitution",
        "sustitución"
      ],
      [
        "termination",
        "terminación"
      ],
      [
        "transformation",
        "transformación"
      ],
      [
        "translation",
        "traducción"
      ],
      [
        "transportation",
        "transportación"
      ],
      [
        "unification",
        "unificación"
      ],
      [
        "utilization",
        "utilización"
      ],
      [
        "vaccination",
        "vacunación"
      ],
      [
        "validation",
        "validación"
      ],
      [
        "variation",
        "variación"
      ],
      [
        "ventilation",
        "ventilación"
      ],
      [
        "verification",
        "verificación"
      ],
      [
        "vibration",
        "vibración"
      ],
      [
        "visualization",
        "visualización"
      ]
    ]
  },
  "ity-idad": {
    "id": "ity-idad",
    "title": "-ity → -idad",
    "explanation": "Many English nouns ending in -ity have a related Spanish noun ending in -idad.",
    "listenLanguage": "es-ES",
    "words": [
      [
        "accessibility",
        "accesibilidad"
      ],
      [
        "activity",
        "actividad"
      ],
      [
        "actuality",
        "actualidad"
      ],
      [
        "adaptability",
        "adaptabilidad"
      ],
      [
        "affinity",
        "afinidad"
      ],
      [
        "authority",
        "autoridad"
      ],
      [
        "capacity",
        "capacidad"
      ],
      [
        "celebrity",
        "celebridad"
      ],
      [
        "clarity",
        "claridad"
      ],
      [
        "community",
        "comunidad"
      ],
      [
        "complexity",
        "complejidad"
      ],
      [
        "curiosity",
        "curiosidad"
      ],
      [
        "density",
        "densidad"
      ],
      [
        "diversity",
        "diversidad"
      ],
      [
        "electricity",
        "electricidad"
      ],
      [
        "eternity",
        "eternidad"
      ],
      [
        "facility",
        "facilidad"
      ],
      [
        "familiarity",
        "familiaridad"
      ],
      [
        "fertility",
        "fertilidad"
      ],
      [
        "flexibility",
        "flexibilidad"
      ],
      [
        "formality",
        "formalidad"
      ],
      [
        "fragility",
        "fragilidad"
      ],
      [
        "functionality",
        "funcionalidad"
      ],
      [
        "generosity",
        "generosidad"
      ],
      [
        "hostility",
        "hostilidad"
      ],
      [
        "humanity",
        "humanidad"
      ],
      [
        "identity",
        "identidad"
      ],
      [
        "immunity",
        "inmunidad"
      ],
      [
        "intensity",
        "intensidad"
      ],
      [
        "legality",
        "legalidad"
      ],
      [
        "locality",
        "localidad"
      ],
      [
        "mobility",
        "movilidad"
      ],
      [
        "nationality",
        "nacionalidad"
      ],
      [
        "necessity",
        "necesidad"
      ],
      [
        "normality",
        "normalidad"
      ],
      [
        "objectivity",
        "objetividad"
      ],
      [
        "opportunity",
        "oportunidad"
      ],
      [
        "originality",
        "originalidad"
      ],
      [
        "personality",
        "personalidad"
      ],
      [
        "possibility",
        "posibilidad"
      ],
      [
        "priority",
        "prioridad"
      ],
      [
        "probability",
        "probabilidad"
      ],
      [
        "productivity",
        "productividad"
      ],
      [
        "publicity",
        "publicidad"
      ],
      [
        "quality",
        "calidad"
      ],
      [
        "quantity",
        "cantidad"
      ],
      [
        "reality",
        "realidad"
      ],
      [
        "responsibility",
        "responsabilidad"
      ],
      [
        "security",
        "seguridad"
      ],
      [
        "sensitivity",
        "sensibilidad"
      ],
      [
        "simplicity",
        "simplicidad"
      ],
      [
        "solidarity",
        "solidaridad"
      ],
      [
        "stability",
        "estabilidad"
      ],
      [
        "superiority",
        "superioridad"
      ],
      [
        "sustainability",
        "sostenibilidad"
      ],
      [
        "totality",
        "totalidad"
      ],
      [
        "university",
        "universidad"
      ],
      [
        "utility",
        "utilidad"
      ],
      [
        "variety",
        "variedad"
      ],
      [
        "velocity",
        "velocidad"
      ],
      [
        "visibility",
        "visibilidad"
      ],
      [
        "vulnerability",
        "vulnerabilidad"
      ]
    ]
  },
  "ous-oso": {
    "id": "ous-oso",
    "title": "-ous → -oso / -osa",
    "explanation": "Many English adjectives ending in -ous have a related Spanish adjective ending in -oso or -osa.",
    "listenLanguage": "es-ES",
    "words": [
      [
        "ambitious",
        "ambicioso"
      ],
      [
        "anxious",
        "ansioso"
      ],
      [
        "ceremonious",
        "ceremonioso"
      ],
      [
        "contagious",
        "contagioso"
      ],
      [
        "curious",
        "curioso"
      ],
      [
        "delicious",
        "delicioso"
      ],
      [
        "fabulous",
        "fabuloso"
      ],
      [
        "famous",
        "famoso"
      ],
      [
        "furious",
        "furioso"
      ],
      [
        "generous",
        "generoso"
      ],
      [
        "glorious",
        "glorioso"
      ],
      [
        "harmonious",
        "armonioso"
      ],
      [
        "infectious",
        "infeccioso"
      ],
      [
        "laborious",
        "laborioso"
      ],
      [
        "luminous",
        "luminoso"
      ],
      [
        "malicious",
        "malicioso"
      ],
      [
        "marvelous",
        "maravilloso"
      ],
      [
        "mysterious",
        "misterioso"
      ],
      [
        "nervous",
        "nervioso"
      ],
      [
        "numerous",
        "numeroso"
      ],
      [
        "precious",
        "precioso"
      ],
      [
        "religious",
        "religioso"
      ],
      [
        "rigorous",
        "riguroso"
      ],
      [
        "scandalous",
        "escandaloso"
      ],
      [
        "spacious",
        "espacioso"
      ],
      [
        "studious",
        "estudioso"
      ],
      [
        "superstitious",
        "supersticioso"
      ],
      [
        "tedious",
        "tedioso"
      ],
      [
        "vicious",
        "vicioso"
      ],
      [
        "vigorous",
        "vigoroso"
      ],
      [
        "voluminous",
        "voluminoso"
      ]
    ]
  },
  "ly-mente": {
    "id": "ly-mente",
    "title": "-ly → -mente",
    "explanation": "Many English adverbs ending in -ly correspond to Spanish adverbs ending in -mente.",
    "listenLanguage": "es-ES",
    "words": [
      [
        "absolutely",
        "absolutamente"
      ],
      [
        "actively",
        "activamente"
      ],
      [
        "approximately",
        "aproximadamente"
      ],
      [
        "automatically",
        "automáticamente"
      ],
      [
        "basically",
        "básicamente"
      ],
      [
        "certainly",
        "ciertamente"
      ],
      [
        "clearly",
        "claramente"
      ],
      [
        "completely",
        "completamente"
      ],
      [
        "constantly",
        "constantemente"
      ],
      [
        "correctly",
        "correctamente"
      ],
      [
        "directly",
        "directamente"
      ],
      [
        "easily",
        "fácilmente"
      ],
      [
        "economically",
        "económicamente"
      ],
      [
        "especially",
        "especialmente"
      ],
      [
        "evidently",
        "evidentemente"
      ],
      [
        "exactly",
        "exactamente"
      ],
      [
        "finally",
        "finalmente"
      ],
      [
        "formally",
        "formalmente"
      ],
      [
        "fortunately",
        "afortunadamente"
      ],
      [
        "frequently",
        "frecuentemente"
      ],
      [
        "generally",
        "generalmente"
      ],
      [
        "gradually",
        "gradualmente"
      ],
      [
        "historically",
        "históricamente"
      ],
      [
        "immediately",
        "inmediatamente"
      ],
      [
        "individually",
        "individualmente"
      ],
      [
        "legally",
        "legalmente"
      ],
      [
        "literally",
        "literalmente"
      ],
      [
        "logically",
        "lógicamente"
      ],
      [
        "manually",
        "manualmente"
      ],
      [
        "naturally",
        "naturalmente"
      ],
      [
        "normally",
        "normalmente"
      ],
      [
        "officially",
        "oficialmente"
      ],
      [
        "originally",
        "originalmente"
      ],
      [
        "partially",
        "parcialmente"
      ],
      [
        "perfectly",
        "perfectamente"
      ],
      [
        "personally",
        "personalmente"
      ],
      [
        "politically",
        "políticamente"
      ],
      [
        "possibly",
        "posiblemente"
      ],
      [
        "practically",
        "prácticamente"
      ],
      [
        "precisely",
        "precisamente"
      ],
      [
        "probably",
        "probablemente"
      ],
      [
        "publicly",
        "públicamente"
      ],
      [
        "rapidly",
        "rápidamente"
      ],
      [
        "recently",
        "recientemente"
      ],
      [
        "regularly",
        "regularmente"
      ],
      [
        "relatively",
        "relativamente"
      ],
      [
        "scientifically",
        "científicamente"
      ],
      [
        "seriously",
        "seriamente"
      ],
      [
        "simply",
        "simplemente"
      ],
      [
        "slowly",
        "lentamente"
      ],
      [
        "specifically",
        "específicamente"
      ],
      [
        "temporarily",
        "temporalmente"
      ],
      [
        "totally",
        "totalmente"
      ],
      [
        "traditionally",
        "tradicionalmente"
      ],
      [
        "typically",
        "típicamente"
      ],
      [
        "usually",
        "usualmente"
      ],
      [
        "visually",
        "visualmente"
      ]
    ]
  },
  "ph-f": {
    "id": "ph-f",
    "title": "ph → f",
    "explanation": "Many English words written with ph have a related Spanish word written with f.",
    "listenLanguage": "es-ES",
    "words": [
      [
        "alphabet",
        "alfabeto"
      ],
      [
        "apostrophe",
        "apóstrofo"
      ],
      [
        "atmosphere",
        "atmósfera"
      ],
      [
        "bibliography",
        "bibliografía"
      ],
      [
        "biographical",
        "biográfico"
      ],
      [
        "biography",
        "biografía"
      ],
      [
        "catastrophe",
        "catástrofe"
      ],
      [
        "dolphin",
        "delfín"
      ],
      [
        "elephant",
        "elefante"
      ],
      [
        "emphasis",
        "énfasis"
      ],
      [
        "geographic",
        "geográfico"
      ],
      [
        "geography",
        "geografía"
      ],
      [
        "metaphor",
        "metáfora"
      ],
      [
        "microphone",
        "micrófono"
      ],
      [
        "orthography",
        "ortografía"
      ],
      [
        "paragraph",
        "párrafo"
      ],
      [
        "pharmacy",
        "farmacia"
      ],
      [
        "phase",
        "fase"
      ],
      [
        "phenomenon",
        "fenómeno"
      ],
      [
        "philanthropy",
        "filantropía"
      ],
      [
        "philosophy",
        "filosofía"
      ],
      [
        "phobia",
        "fobia"
      ],
      [
        "phonetic",
        "fonético"
      ],
      [
        "phonetics",
        "fonética"
      ],
      [
        "phonology",
        "fonología"
      ],
      [
        "phosphorus",
        "fósforo"
      ],
      [
        "photo",
        "foto"
      ],
      [
        "photograph",
        "fotografía"
      ],
      [
        "photographer",
        "fotógrafo"
      ],
      [
        "photographic",
        "fotográfico"
      ],
      [
        "photography",
        "fotografía"
      ],
      [
        "phrase",
        "frase"
      ],
      [
        "physical",
        "físico"
      ],
      [
        "physics",
        "física"
      ],
      [
        "prophecy",
        "profecía"
      ],
      [
        "prophet",
        "profeta"
      ],
      [
        "sphere",
        "esfera"
      ],
      [
        "symphony",
        "sinfonía"
      ],
      [
        "telephone",
        "teléfono"
      ],
      [
        "telephony",
        "telefonía"
      ],
      [
        "topography",
        "topografía"
      ],
      [
        "trophy",
        "trofeo"
      ],
      [
        "typography",
        "tipografía"
      ]
    ]
  },
  "ic-ico": {
    "id": "ic-ico",
    "title": "-ic → -ico / -ica",
    "explanation": "Many English adjectives ending in -ic have a related Spanish form ending in -ico or -ica.",
    "listenLanguage": "es-ES",
    "words": [
      [
        "academic",
        "académico"
      ],
      [
        "acoustic",
        "acústico"
      ],
      [
        "alcoholic",
        "alcohólico"
      ],
      [
        "allergic",
        "alérgico"
      ],
      [
        "artistic",
        "artístico"
      ],
      [
        "automatic",
        "automático"
      ],
      [
        "basic",
        "básico"
      ],
      [
        "classic",
        "clásico"
      ],
      [
        "comic",
        "cómico"
      ],
      [
        "cosmic",
        "cósmico"
      ],
      [
        "democratic",
        "democrático"
      ],
      [
        "dramatic",
        "dramático"
      ],
      [
        "dynamic",
        "dinámico"
      ],
      [
        "economic",
        "económico"
      ],
      [
        "electric",
        "eléctrico"
      ],
      [
        "electronic",
        "electrónico"
      ],
      [
        "energetic",
        "energético"
      ],
      [
        "fantastic",
        "fantástico"
      ],
      [
        "genetic",
        "genético"
      ],
      [
        "geographic",
        "geográfico"
      ],
      [
        "geologic",
        "geológico"
      ],
      [
        "geometric",
        "geométrico"
      ],
      [
        "historic",
        "histórico"
      ],
      [
        "ironic",
        "irónico"
      ],
      [
        "magic",
        "mágico"
      ],
      [
        "magnetic",
        "magnético"
      ],
      [
        "mechanic",
        "mecánico"
      ],
      [
        "metallic",
        "metálico"
      ],
      [
        "numeric",
        "numérico"
      ],
      [
        "organic",
        "orgánico"
      ],
      [
        "panic",
        "pánico"
      ],
      [
        "photographic",
        "fotográfico"
      ],
      [
        "plastic",
        "plástico"
      ],
      [
        "poetic",
        "poético"
      ],
      [
        "political",
        "político"
      ],
      [
        "public",
        "público"
      ],
      [
        "rhythmic",
        "rítmico"
      ],
      [
        "romantic",
        "romántico"
      ],
      [
        "scientific",
        "científico"
      ],
      [
        "specific",
        "específico"
      ],
      [
        "strategic",
        "estratégico"
      ],
      [
        "symbolic",
        "simbólico"
      ],
      [
        "systematic",
        "sistemático"
      ],
      [
        "toxic",
        "tóxico"
      ],
      [
        "tragic",
        "trágico"
      ],
      [
        "typical",
        "típico"
      ],
      [
        "volcanic",
        "volcánico"
      ]
    ]
  },
  "ive-ivo": {
    "id": "ive-ivo",
    "title": "-ive → -ivo / -iva",
    "explanation": "Many English adjectives ending in -ive have a related Spanish adjective ending in -ivo or -iva.",
    "listenLanguage": "es-ES",
    "words": [
      [
        "active",
        "activo"
      ],
      [
        "adaptive",
        "adaptativo"
      ],
      [
        "administrative",
        "administrativo"
      ],
      [
        "affirmative",
        "afirmativo"
      ],
      [
        "aggressive",
        "agresivo"
      ],
      [
        "alternative",
        "alternativo"
      ],
      [
        "attractive",
        "atractivo"
      ],
      [
        "collective",
        "colectivo"
      ],
      [
        "comparative",
        "comparativo"
      ],
      [
        "competitive",
        "competitivo"
      ],
      [
        "cooperative",
        "cooperativo"
      ],
      [
        "creative",
        "creativo"
      ],
      [
        "decisive",
        "decisivo"
      ],
      [
        "decorative",
        "decorativo"
      ],
      [
        "defensive",
        "defensivo"
      ],
      [
        "demonstrative",
        "demostrativo"
      ],
      [
        "descriptive",
        "descriptivo"
      ],
      [
        "distinctive",
        "distintivo"
      ],
      [
        "effective",
        "efectivo"
      ],
      [
        "excessive",
        "excesivo"
      ],
      [
        "exclusive",
        "exclusivo"
      ],
      [
        "executive",
        "ejecutivo"
      ],
      [
        "expansive",
        "expansivo"
      ],
      [
        "explosive",
        "explosivo"
      ],
      [
        "expressive",
        "expresivo"
      ],
      [
        "indicative",
        "indicativo"
      ],
      [
        "intensive",
        "intensivo"
      ],
      [
        "legislative",
        "legislativo"
      ],
      [
        "native",
        "nativo"
      ],
      [
        "negative",
        "negativo"
      ],
      [
        "objective",
        "objetivo"
      ],
      [
        "operative",
        "operativo"
      ],
      [
        "passive",
        "pasivo"
      ],
      [
        "positive",
        "positivo"
      ],
      [
        "preventive",
        "preventivo"
      ],
      [
        "primitive",
        "primitivo"
      ],
      [
        "productive",
        "productivo"
      ],
      [
        "progressive",
        "progresivo"
      ],
      [
        "reactive",
        "reactivo"
      ],
      [
        "relative",
        "relativo"
      ],
      [
        "representative",
        "representativo"
      ],
      [
        "restrictive",
        "restrictivo"
      ],
      [
        "selective",
        "selectivo"
      ],
      [
        "speculative",
        "especulativo"
      ],
      [
        "subjective",
        "subjetivo"
      ],
      [
        "successive",
        "sucesivo"
      ]
    ]
  },
  "ist-ista": {
    "id": "ist-ista",
    "title": "-ist → -ista",
    "explanation": "Many English nouns ending in -ist have a closely related Spanish noun ending in -ista.",
    "listenLanguage": "es-ES",
    "words": [
      [
        "activist",
        "activista"
      ],
      [
        "artist",
        "artista"
      ],
      [
        "capitalist",
        "capitalista"
      ],
      [
        "communist",
        "comunista"
      ],
      [
        "cyclist",
        "ciclista"
      ],
      [
        "dentist",
        "dentista"
      ],
      [
        "fascist",
        "fascista"
      ],
      [
        "feminist",
        "feminista"
      ],
      [
        "finalist",
        "finalista"
      ],
      [
        "florist",
        "florista"
      ],
      [
        "guitarist",
        "guitarrista"
      ],
      [
        "idealist",
        "idealista"
      ],
      [
        "linguist",
        "lingüista"
      ],
      [
        "materialist",
        "materialista"
      ],
      [
        "minimalist",
        "minimalista"
      ],
      [
        "modernist",
        "modernista"
      ],
      [
        "motorist",
        "motorista"
      ],
      [
        "nationalist",
        "nacionalista"
      ],
      [
        "novelist",
        "novelista"
      ],
      [
        "optimist",
        "optimista"
      ],
      [
        "pacifist",
        "pacifista"
      ],
      [
        "pessimist",
        "pesimista"
      ],
      [
        "pianist",
        "pianista"
      ],
      [
        "pluralist",
        "pluralista"
      ],
      [
        "realist",
        "realista"
      ],
      [
        "receptionist",
        "recepcionista"
      ],
      [
        "socialist",
        "socialista"
      ],
      [
        "soloist",
        "solista"
      ],
      [
        "specialist",
        "especialista"
      ],
      [
        "stylist",
        "estilista"
      ],
      [
        "tourist",
        "turista"
      ],
      [
        "violinist",
        "violinista"
      ]
    ]
  },
  "ance-encia": {
    "id": "ance-encia",
    "title": "-ance / -ence → -ancia / -encia",
    "explanation": "Many English nouns ending in -ance or -ence have a related Spanish noun ending in -ancia or -encia.",
    "listenLanguage": "es-ES",
    "words": [
      [
        "absence",
        "ausencia"
      ],
      [
        "abundance",
        "abundancia"
      ],
      [
        "assistance",
        "asistencia"
      ],
      [
        "audience",
        "audiencia"
      ],
      [
        "circumstance",
        "circunstancia"
      ],
      [
        "coincidence",
        "coincidencia"
      ],
      [
        "competence",
        "competencia"
      ],
      [
        "conference",
        "conferencia"
      ],
      [
        "conscience",
        "conciencia"
      ],
      [
        "consequence",
        "consecuencia"
      ],
      [
        "correspondence",
        "correspondencia"
      ],
      [
        "dependence",
        "dependencia"
      ],
      [
        "difference",
        "diferencia"
      ],
      [
        "distance",
        "distancia"
      ],
      [
        "elegance",
        "elegancia"
      ],
      [
        "evidence",
        "evidencia"
      ],
      [
        "excellence",
        "excelencia"
      ],
      [
        "existence",
        "existencia"
      ],
      [
        "experience",
        "experiencia"
      ],
      [
        "frequency",
        "frecuencia"
      ],
      [
        "ignorance",
        "ignorancia"
      ],
      [
        "importance",
        "importancia"
      ],
      [
        "independence",
        "independencia"
      ],
      [
        "influence",
        "influencia"
      ],
      [
        "innocence",
        "inocencia"
      ],
      [
        "instance",
        "instancia"
      ],
      [
        "intelligence",
        "inteligencia"
      ],
      [
        "obedience",
        "obediencia"
      ],
      [
        "patience",
        "paciencia"
      ],
      [
        "persistence",
        "persistencia"
      ],
      [
        "preference",
        "preferencia"
      ],
      [
        "presence",
        "presencia"
      ],
      [
        "relevance",
        "relevancia"
      ],
      [
        "resistance",
        "resistencia"
      ],
      [
        "substance",
        "sustancia"
      ],
      [
        "tolerance",
        "tolerancia"
      ],
      [
        "transcendence",
        "trascendencia"
      ],
      [
        "violence",
        "violencia"
      ]
    ]
  }
};
