window.LANGUAGE_DNA_PATTERN_DICTIONARIES={
  "tion-cion": {
    "id": "tion-cion",
    "title": "-tion → -ción",
    "explanation": "Many English nouns ending in -tion have a closely related Spanish form ending in -ción.",
    "listenLanguage": "es-ES",
    "words": [
      [
        "abbreviation",
        "abreviación"
      ],
      [
        "abstraction",
        "abstracción"
      ],
      [
        "acceleration",
        "aceleración"
      ],
      [
        "accusation",
        "acusación"
      ],
      [
        "acquisition",
        "adquisición"
      ],
      [
        "action",
        "acción"
      ],
      [
        "activation",
        "activación"
      ],
      [
        "adaptation",
        "adaptación"
      ],
      [
        "addition",
        "adición"
      ],
      [
        "administration",
        "administración"
      ],
      [
        "admiration",
        "admiración"
      ],
      [
        "adoption",
        "adopción"
      ],
      [
        "affirmation",
        "afirmación"
      ],
      [
        "agitation",
        "agitación"
      ],
      [
        "allocation",
        "asignación"
      ],
      [
        "alteration",
        "alteración"
      ],
      [
        "ambition",
        "ambición"
      ],
      [
        "amplification",
        "amplificación"
      ],
      [
        "animation",
        "animación"
      ],
      [
        "anticipation",
        "anticipación"
      ],
      [
        "application",
        "aplicación"
      ],
      [
        "appreciation",
        "apreciación"
      ],
      [
        "articulation",
        "articulación"
      ],
      [
        "assimilation",
        "asimilación"
      ],
      [
        "association",
        "asociación"
      ],
      [
        "attention",
        "atención"
      ],
      [
        "attraction",
        "atracción"
      ],
      [
        "authentication",
        "autenticación"
      ],
      [
        "authorization",
        "autorización"
      ],
      [
        "automation",
        "automatización"
      ],
      [
        "calculation",
        "calculación"
      ],
      [
        "cancellation",
        "cancelación"
      ],
      [
        "celebration",
        "celebración"
      ],
      [
        "certification",
        "certificación"
      ],
      [
        "circulation",
        "circulación"
      ],
      [
        "citation",
        "citación"
      ],
      [
        "civilization",
        "civilización"
      ],
      [
        "classification",
        "clasificación"
      ],
      [
        "collaboration",
        "colaboración"
      ],
      [
        "collection",
        "colección"
      ],
      [
        "combination",
        "combinación"
      ],
      [
        "communication",
        "comunicación"
      ],
      [
        "compensation",
        "compensación"
      ],
      [
        "competition",
        "competición"
      ],
      [
        "complication",
        "complicación"
      ],
      [
        "composition",
        "composición"
      ],
      [
        "concentration",
        "concentración"
      ],
      [
        "conception",
        "concepción"
      ],
      [
        "condition",
        "condición"
      ],
      [
        "configuration",
        "configuración"
      ],
      [
        "confirmation",
        "confirmación"
      ],
      [
        "confrontation",
        "confrontación"
      ],
      [
        "congregation",
        "congregación"
      ],
      [
        "conjugation",
        "conjugación"
      ],
      [
        "conservation",
        "conservación"
      ],
      [
        "consideration",
        "consideración"
      ],
      [
        "constellation",
        "constelación"
      ],
      [
        "construction",
        "construcción"
      ],
      [
        "consultation",
        "consulta"
      ],
      [
        "contamination",
        "contaminación"
      ],
      [
        "continuation",
        "continuación"
      ],
      [
        "contribution",
        "contribución"
      ],
      [
        "conversation",
        "conversación"
      ],
      [
        "cooperation",
        "cooperación"
      ],
      [
        "coordination",
        "coordinación"
      ],
      [
        "creation",
        "creación"
      ],
      [
        "cultivation",
        "cultivación"
      ],
      [
        "declaration",
        "declaración"
      ],
      [
        "decoration",
        "decoración"
      ],
      [
        "dedication",
        "dedicación"
      ],
      [
        "definition",
        "definición"
      ],
      [
        "degradation",
        "degradación"
      ],
      [
        "delegation",
        "delegación"
      ],
      [
        "demonstration",
        "demostración"
      ],
      [
        "deportation",
        "deportación"
      ],
      [
        "description",
        "descripción"
      ],
      [
        "determination",
        "determinación"
      ],
      [
        "deviation",
        "desviación"
      ],
      [
        "differentiation",
        "diferenciación"
      ],
      [
        "digitalization",
        "digitalización"
      ],
      [
        "direction",
        "dirección"
      ],
      [
        "disconnection",
        "desconexión"
      ],
      [
        "discrimination",
        "discriminación"
      ],
      [
        "distribution",
        "distribución"
      ],
      [
        "documentation",
        "documentación"
      ],
      [
        "donation",
        "donación"
      ],
      [
        "duration",
        "duración"
      ],
      [
        "edition",
        "edición"
      ],
      [
        "education",
        "educación"
      ],
      [
        "election",
        "elección"
      ],
      [
        "elimination",
        "eliminación"
      ],
      [
        "emotion",
        "emoción"
      ],
      [
        "enumeration",
        "enumeración"
      ],
      [
        "evacuation",
        "evacuación"
      ],
      [
        "evaluation",
        "evaluación"
      ],
      [
        "evaporation",
        "evaporación"
      ],
      [
        "evolution",
        "evolución"
      ],
      [
        "excavation",
        "excavación"
      ],
      [
        "exception",
        "excepción"
      ],
      [
        "exclamation",
        "exclamación"
      ],
      [
        "exhibition",
        "exhibición"
      ],
      [
        "explanation",
        "explicación"
      ],
      [
        "exploration",
        "exploración"
      ],
      [
        "expression",
        "expresión"
      ],
      [
        "fabrication",
        "fabricación"
      ],
      [
        "federation",
        "federación"
      ],
      [
        "fertilization",
        "fertilización"
      ],
      [
        "filtration",
        "filtración"
      ],
      [
        "formation",
        "formación"
      ],
      [
        "foundation",
        "fundación"
      ],
      [
        "fragmentation",
        "fragmentación"
      ],
      [
        "frustration",
        "frustración"
      ],
      [
        "function",
        "función"
      ],
      [
        "generalization",
        "generalización"
      ],
      [
        "generation",
        "generación"
      ],
      [
        "globalization",
        "globalización"
      ],
      [
        "graduation",
        "graduación"
      ],
      [
        "identification",
        "identificación"
      ],
      [
        "illumination",
        "iluminación"
      ],
      [
        "illustration",
        "ilustración"
      ],
      [
        "imagination",
        "imaginación"
      ],
      [
        "imitation",
        "imitación"
      ],
      [
        "immigration",
        "inmigración"
      ],
      [
        "implantation",
        "implantación"
      ],
      [
        "implementation",
        "implementación"
      ],
      [
        "inclination",
        "inclinación"
      ],
      [
        "incorporation",
        "incorporación"
      ],
      [
        "indication",
        "indicación"
      ],
      [
        "inflation",
        "inflación"
      ],
      [
        "information",
        "información"
      ],
      [
        "inhalation",
        "inhalación"
      ],
      [
        "innovation",
        "innovación"
      ],
      [
        "inspection",
        "inspección"
      ],
      [
        "installation",
        "instalación"
      ],
      [
        "institution",
        "institución"
      ],
      [
        "integration",
        "integración"
      ],
      [
        "interpretation",
        "interpretación"
      ],
      [
        "intervention",
        "intervención"
      ],
      [
        "introduction",
        "introducción"
      ],
      [
        "invention",
        "invención"
      ],
      [
        "investigation",
        "investigación"
      ],
      [
        "invitation",
        "invitación"
      ],
      [
        "justification",
        "justificación"
      ],
      [
        "legislation",
        "legislación"
      ],
      [
        "legitimation",
        "legitimación"
      ],
      [
        "liberation",
        "liberación"
      ],
      [
        "limitation",
        "limitación"
      ],
      [
        "localization",
        "localización"
      ],
      [
        "manipulation",
        "manipulación"
      ],
      [
        "meditation",
        "meditación"
      ],
      [
        "migration",
        "migración"
      ],
      [
        "modernization",
        "modernización"
      ],
      [
        "modification",
        "modificación"
      ],
      [
        "motivation",
        "motivación"
      ],
      [
        "mutation",
        "mutación"
      ],
      [
        "navigation",
        "navegación"
      ],
      [
        "negotiation",
        "negociación"
      ],
      [
        "neutralization",
        "neutralización"
      ],
      [
        "nomination",
        "nominación"
      ],
      [
        "notification",
        "notificación"
      ],
      [
        "observation",
        "observación"
      ],
      [
        "occupation",
        "ocupación"
      ],
      [
        "operation",
        "operación"
      ],
      [
        "optimization",
        "optimización"
      ],
      [
        "organization",
        "organización"
      ],
      [
        "orientation",
        "orientación"
      ],
      [
        "oxidation",
        "oxidación"
      ],
      [
        "participation",
        "participación"
      ],
      [
        "perforation",
        "perforación"
      ],
      [
        "plantation",
        "plantación"
      ],
      [
        "polarization",
        "polarización"
      ],
      [
        "population",
        "población"
      ],
      [
        "position",
        "posición"
      ],
      [
        "prediction",
        "predicción"
      ],
      [
        "preparation",
        "preparación"
      ],
      [
        "presentation",
        "presentación"
      ],
      [
        "preservation",
        "preservación"
      ],
      [
        "prevention",
        "prevención"
      ],
      [
        "privatization",
        "privatización"
      ],
      [
        "proclamation",
        "proclamación"
      ],
      [
        "production",
        "producción"
      ],
      [
        "projection",
        "proyección"
      ],
      [
        "pronunciation",
        "pronunciación"
      ],
      [
        "proportion",
        "proporción"
      ],
      [
        "protection",
        "protección"
      ],
      [
        "publication",
        "publicación"
      ],
      [
        "punctuation",
        "puntuación"
      ],
      [
        "qualification",
        "cualificación"
      ],
      [
        "radiation",
        "radiación"
      ],
      [
        "reaction",
        "reacción"
      ],
      [
        "recommendation",
        "recomendación"
      ],
      [
        "reconciliation",
        "reconciliación"
      ],
      [
        "reconstruction",
        "reconstrucción"
      ],
      [
        "recreation",
        "recreación"
      ],
      [
        "reduction",
        "reducción"
      ],
      [
        "regulation",
        "regulación"
      ],
      [
        "relation",
        "relación"
      ],
      [
        "relaxation",
        "relajación"
      ],
      [
        "renovation",
        "renovación"
      ],
      [
        "repetition",
        "repetición"
      ],
      [
        "representation",
        "representación"
      ],
      [
        "reproduction",
        "reproducción"
      ],
      [
        "reservation",
        "reservación"
      ],
      [
        "resolution",
        "resolución"
      ],
      [
        "restoration",
        "restauración"
      ],
      [
        "rotation",
        "rotación"
      ],
      [
        "satisfaction",
        "satisfacción"
      ],
      [
        "section",
        "sección"
      ],
      [
        "segmentation",
        "segmentación"
      ],
      [
        "selection",
        "selección"
      ],
      [
        "separation",
        "separación"
      ],
      [
        "simulation",
        "simulación"
      ],
      [
        "situation",
        "situación"
      ],
      [
        "solution",
        "solución"
      ],
      [
        "specialization",
        "especialización"
      ],
      [
        "specification",
        "especificación"
      ],
      [
        "station",
        "estación"
      ],
      [
        "substitution",
        "sustitución"
      ],
      [
        "synchronization",
        "sincronización"
      ],
      [
        "termination",
        "terminación"
      ],
      [
        "transcription",
        "transcripción"
      ],
      [
        "transformation",
        "transformación"
      ],
      [
        "translation",
        "traducción"
      ],
      [
        "transportation",
        "transportación"
      ],
      [
        "unification",
        "unificación"
      ],
      [
        "utilization",
        "utilización"
      ],
      [
        "vaccination",
        "vacunación"
      ],
      [
        "validation",
        "validación"
      ],
      [
        "variation",
        "variación"
      ],
      [
        "ventilation",
        "ventilación"
      ],
      [
        "verification",
        "verificación"
      ],
      [
        "vibration",
        "vibración"
      ],
      [
        "visualization",
        "visualización"
      ]
    ]
  },
  "ity-idad": {
    "id": "ity-idad",
    "title": "-ity → -idad",
    "explanation": "Many English nouns ending in -ity have a related Spanish noun ending in -idad.",
    "listenLanguage": "es-ES",
    "words": [
      [
        "accessibility",
        "accesibilidad"
      ],
      [
        "activity",
        "actividad"
      ],
      [
        "actuality",
        "actualidad"
      ],
      [
        "adaptability",
        "adaptabilidad"
      ],
      [
        "affinity",
        "afinidad"
      ],
      [
        "agility",
        "agilidad"
      ],
      [
        "anonymity",
        "anonimidad"
      ],
      [
        "authority",
        "autoridad"
      ],
      [
        "capacity",
        "capacidad"
      ],
      [
        "celebrity",
        "celebridad"
      ],
      [
        "clarity",
        "claridad"
      ],
      [
        "community",
        "comunidad"
      ],
      [
        "complexity",
        "complejidad"
      ],
      [
        "curiosity",
        "curiosidad"
      ],
      [
        "density",
        "densidad"
      ],
      [
        "diversity",
        "diversidad"
      ],
      [
        "elasticity",
        "elasticidad"
      ],
      [
        "electricity",
        "electricidad"
      ],
      [
        "eternity",
        "eternidad"
      ],
      [
        "facility",
        "facilidad"
      ],
      [
        "familiarity",
        "familiaridad"
      ],
      [
        "fertility",
        "fertilidad"
      ],
      [
        "flexibility",
        "flexibilidad"
      ],
      [
        "formality",
        "formalidad"
      ],
      [
        "fragility",
        "fragilidad"
      ],
      [
        "functionality",
        "funcionalidad"
      ],
      [
        "generality",
        "generalidad"
      ],
      [
        "generosity",
        "generosidad"
      ],
      [
        "hospitality",
        "hospitalidad"
      ],
      [
        "hostility",
        "hostilidad"
      ],
      [
        "humanity",
        "humanidad"
      ],
      [
        "identity",
        "identidad"
      ],
      [
        "immunity",
        "inmunidad"
      ],
      [
        "individuality",
        "individualidad"
      ],
      [
        "inferiority",
        "inferioridad"
      ],
      [
        "instability",
        "inestabilidad"
      ],
      [
        "intensity",
        "intensidad"
      ],
      [
        "legality",
        "legalidad"
      ],
      [
        "locality",
        "localidad"
      ],
      [
        "mobility",
        "movilidad"
      ],
      [
        "modality",
        "modalidad"
      ],
      [
        "nationality",
        "nacionalidad"
      ],
      [
        "necessity",
        "necesidad"
      ],
      [
        "neutrality",
        "neutralidad"
      ],
      [
        "normality",
        "normalidad"
      ],
      [
        "objectivity",
        "objetividad"
      ],
      [
        "opportunity",
        "oportunidad"
      ],
      [
        "originality",
        "originalidad"
      ],
      [
        "personality",
        "personalidad"
      ],
      [
        "plurality",
        "pluralidad"
      ],
      [
        "possibility",
        "posibilidad"
      ],
      [
        "priority",
        "prioridad"
      ],
      [
        "probability",
        "probabilidad"
      ],
      [
        "productivity",
        "productividad"
      ],
      [
        "publicity",
        "publicidad"
      ],
      [
        "quality",
        "calidad"
      ],
      [
        "quantity",
        "cantidad"
      ],
      [
        "reality",
        "realidad"
      ],
      [
        "regularity",
        "regularidad"
      ],
      [
        "responsibility",
        "responsabilidad"
      ],
      [
        "security",
        "seguridad"
      ],
      [
        "sensitivity",
        "sensibilidad"
      ],
      [
        "sexuality",
        "sexualidad"
      ],
      [
        "simplicity",
        "simplicidad"
      ],
      [
        "singularity",
        "singularidad"
      ],
      [
        "solidarity",
        "solidaridad"
      ],
      [
        "specificity",
        "especificidad"
      ],
      [
        "spontaneity",
        "espontaneidad"
      ],
      [
        "stability",
        "estabilidad"
      ],
      [
        "subjectivity",
        "subjetividad"
      ],
      [
        "superiority",
        "superioridad"
      ],
      [
        "sustainability",
        "sostenibilidad"
      ],
      [
        "totality",
        "totalidad"
      ],
      [
        "universality",
        "universalidad"
      ],
      [
        "university",
        "universidad"
      ],
      [
        "utility",
        "utilidad"
      ],
      [
        "variety",
        "variedad"
      ],
      [
        "velocity",
        "velocidad"
      ],
      [
        "visibility",
        "visibilidad"
      ],
      [
        "vulnerability",
        "vulnerabilidad"
      ]
    ]
  },
  "ous-oso": {
    "id": "ous-oso",
    "title": "-ous → -oso / -osa",
    "explanation": "Many English adjectives ending in -ous have a related Spanish adjective ending in -oso or -osa.",
    "listenLanguage": "es-ES",
    "words": [
      [
        "ambitious",
        "ambicioso"
      ],
      [
        "anxious",
        "ansioso"
      ],
      [
        "ceremonious",
        "ceremonioso"
      ],
      [
        "contagious",
        "contagioso"
      ],
      [
        "curious",
        "curioso"
      ],
      [
        "delicious",
        "delicioso"
      ],
      [
        "fabulous",
        "fabuloso"
      ],
      [
        "famous",
        "famoso"
      ],
      [
        "furious",
        "furioso"
      ],
      [
        "generous",
        "generoso"
      ],
      [
        "glorious",
        "glorioso"
      ],
      [
        "harmonious",
        "armonioso"
      ],
      [
        "infectious",
        "infeccioso"
      ],
      [
        "laborious",
        "laborioso"
      ],
      [
        "luminous",
        "luminoso"
      ],
      [
        "malicious",
        "malicioso"
      ],
      [
        "marvelous",
        "maravilloso"
      ],
      [
        "mysterious",
        "misterioso"
      ],
      [
        "nervous",
        "nervioso"
      ],
      [
        "numerous",
        "numeroso"
      ],
      [
        "precious",
        "precioso"
      ],
      [
        "religious",
        "religioso"
      ],
      [
        "rigorous",
        "riguroso"
      ],
      [
        "scandalous",
        "escandaloso"
      ],
      [
        "spacious",
        "espacioso"
      ],
      [
        "studious",
        "estudioso"
      ],
      [
        "superstitious",
        "supersticioso"
      ],
      [
        "tedious",
        "tedioso"
      ],
      [
        "vicious",
        "vicioso"
      ],
      [
        "vigorous",
        "vigoroso"
      ],
      [
        "voluminous",
        "voluminoso"
      ]
    ]
  },
  "ly-mente": {
    "id": "ly-mente",
    "title": "-ly → -mente",
    "explanation": "Many English adverbs ending in -ly correspond to Spanish adverbs ending in -mente.",
    "listenLanguage": "es-ES",
    "words": [
      [
        "absolutely",
        "absolutamente"
      ],
      [
        "actively",
        "activamente"
      ],
      [
        "approximately",
        "aproximadamente"
      ],
      [
        "automatically",
        "automáticamente"
      ],
      [
        "basically",
        "básicamente"
      ],
      [
        "certainly",
        "ciertamente"
      ],
      [
        "clearly",
        "claramente"
      ],
      [
        "completely",
        "completamente"
      ],
      [
        "constantly",
        "constantemente"
      ],
      [
        "correctly",
        "correctamente"
      ],
      [
        "directly",
        "directamente"
      ],
      [
        "easily",
        "fácilmente"
      ],
      [
        "economically",
        "económicamente"
      ],
      [
        "especially",
        "especialmente"
      ],
      [
        "evidently",
        "evidentemente"
      ],
      [
        "exactly",
        "exactamente"
      ],
      [
        "finally",
        "finalmente"
      ],
      [
        "formally",
        "formalmente"
      ],
      [
        "fortunately",
        "afortunadamente"
      ],
      [
        "frequently",
        "frecuentemente"
      ],
      [
        "generally",
        "generalmente"
      ],
      [
        "gradually",
        "gradualmente"
      ],
      [
        "historically",
        "históricamente"
      ],
      [
        "immediately",
        "inmediatamente"
      ],
      [
        "individually",
        "individualmente"
      ],
      [
        "legally",
        "legalmente"
      ],
      [
        "literally",
        "literalmente"
      ],
      [
        "logically",
        "lógicamente"
      ],
      [
        "manually",
        "manualmente"
      ],
      [
        "naturally",
        "naturalmente"
      ],
      [
        "normally",
        "normalmente"
      ],
      [
        "officially",
        "oficialmente"
      ],
      [
        "originally",
        "originalmente"
      ],
      [
        "partially",
        "parcialmente"
      ],
      [
        "perfectly",
        "perfectamente"
      ],
      [
        "personally",
        "personalmente"
      ],
      [
        "politically",
        "políticamente"
      ],
      [
        "possibly",
        "posiblemente"
      ],
      [
        "practically",
        "prácticamente"
      ],
      [
        "precisely",
        "precisamente"
      ],
      [
        "probably",
        "probablemente"
      ],
      [
        "publicly",
        "públicamente"
      ],
      [
        "rapidly",
        "rápidamente"
      ],
      [
        "recently",
        "recientemente"
      ],
      [
        "regularly",
        "regularmente"
      ],
      [
        "relatively",
        "relativamente"
      ],
      [
        "scientifically",
        "científicamente"
      ],
      [
        "seriously",
        "seriamente"
      ],
      [
        "simply",
        "simplemente"
      ],
      [
        "slowly",
        "lentamente"
      ],
      [
        "specifically",
        "específicamente"
      ],
      [
        "temporarily",
        "temporalmente"
      ],
      [
        "totally",
        "totalmente"
      ],
      [
        "traditionally",
        "tradicionalmente"
      ],
      [
        "typically",
        "típicamente"
      ],
      [
        "usually",
        "usualmente"
      ],
      [
        "visually",
        "visualmente"
      ]
    ]
  },
  "ph-f": {
    "id": "ph-f",
    "title": "ph → f",
    "explanation": "Many English words written with ph have a related Spanish word written with f.",
    "listenLanguage": "es-ES",
    "words": [
      [
        "alphabet",
        "alfabeto"
      ],
      [
        "apostrophe",
        "apóstrofo"
      ],
      [
        "atmosphere",
        "atmósfera"
      ],
      [
        "bibliography",
        "bibliografía"
      ],
      [
        "biographical",
        "biográfico"
      ],
      [
        "biography",
        "biografía"
      ],
      [
        "catastrophe",
        "catástrofe"
      ],
      [
        "dolphin",
        "delfín"
      ],
      [
        "elephant",
        "elefante"
      ],
      [
        "emphasis",
        "énfasis"
      ],
      [
        "geographic",
        "geográfico"
      ],
      [
        "geography",
        "geografía"
      ],
      [
        "metaphor",
        "metáfora"
      ],
      [
        "microphone",
        "micrófono"
      ],
      [
        "orthography",
        "ortografía"
      ],
      [
        "paragraph",
        "párrafo"
      ],
      [
        "pharmacy",
        "farmacia"
      ],
      [
        "phase",
        "fase"
      ],
      [
        "phenomenon",
        "fenómeno"
      ],
      [
        "philanthropy",
        "filantropía"
      ],
      [
        "philosophy",
        "filosofía"
      ],
      [
        "phobia",
        "fobia"
      ],
      [
        "phonetic",
        "fonético"
      ],
      [
        "phonetics",
        "fonética"
      ],
      [
        "phonology",
        "fonología"
      ],
      [
        "phosphorus",
        "fósforo"
      ],
      [
        "photo",
        "foto"
      ],
      [
        "photograph",
        "fotografía"
      ],
      [
        "photographer",
        "fotógrafo"
      ],
      [
        "photographic",
        "fotográfico"
      ],
      [
        "photography",
        "fotografía"
      ],
      [
        "phrase",
        "frase"
      ],
      [
        "physical",
        "físico"
      ],
      [
        "physics",
        "física"
      ],
      [
        "prophecy",
        "profecía"
      ],
      [
        "prophet",
        "profeta"
      ],
      [
        "sphere",
        "esfera"
      ],
      [
        "symphony",
        "sinfonía"
      ],
      [
        "telephone",
        "teléfono"
      ],
      [
        "telephony",
        "telefonía"
      ],
      [
        "topography",
        "topografía"
      ],
      [
        "trophy",
        "trofeo"
      ],
      [
        "typography",
        "tipografía"
      ]
    ]
  },
  "ic-ico": {
    "id": "ic-ico",
    "title": "-ic → -ico / -ica",
    "explanation": "Many English adjectives ending in -ic have a related Spanish form ending in -ico or -ica.",
    "listenLanguage": "es-ES",
    "words": [
      [
        "academic",
        "académico"
      ],
      [
        "acoustic",
        "acústico"
      ],
      [
        "alcoholic",
        "alcohólico"
      ],
      [
        "allergic",
        "alérgico"
      ],
      [
        "artistic",
        "artístico"
      ],
      [
        "athletic",
        "atlético"
      ],
      [
        "authentic",
        "auténtico"
      ],
      [
        "automatic",
        "automático"
      ],
      [
        "basic",
        "básico"
      ],
      [
        "catholic",
        "católico"
      ],
      [
        "classic",
        "clásico"
      ],
      [
        "clinical",
        "clínico"
      ],
      [
        "comic",
        "cómico"
      ],
      [
        "cosmic",
        "cósmico"
      ],
      [
        "critical",
        "crítico"
      ],
      [
        "democratic",
        "democrático"
      ],
      [
        "diagnostic",
        "diagnóstico"
      ],
      [
        "didactic",
        "didáctico"
      ],
      [
        "dramatic",
        "dramático"
      ],
      [
        "dynamic",
        "dinámico"
      ],
      [
        "ecological",
        "ecológico"
      ],
      [
        "economic",
        "económico"
      ],
      [
        "electric",
        "eléctrico"
      ],
      [
        "electronic",
        "electrónico"
      ],
      [
        "energetic",
        "energético"
      ],
      [
        "epic",
        "épico"
      ],
      [
        "ethical",
        "ético"
      ],
      [
        "exotic",
        "exótico"
      ],
      [
        "fantastic",
        "fantástico"
      ],
      [
        "genetic",
        "genético"
      ],
      [
        "geographic",
        "geográfico"
      ],
      [
        "geologic",
        "geológico"
      ],
      [
        "geometric",
        "geométrico"
      ],
      [
        "graphic",
        "gráfico"
      ],
      [
        "heroic",
        "heroico"
      ],
      [
        "historic",
        "histórico"
      ],
      [
        "ironic",
        "irónico"
      ],
      [
        "linguistic",
        "lingüístico"
      ],
      [
        "magic",
        "mágico"
      ],
      [
        "magnetic",
        "magnético"
      ],
      [
        "mathematical",
        "matemático"
      ],
      [
        "mechanic",
        "mecánico"
      ],
      [
        "metallic",
        "metálico"
      ],
      [
        "musical",
        "musical"
      ],
      [
        "numeric",
        "numérico"
      ],
      [
        "optic",
        "óptico"
      ],
      [
        "organic",
        "orgánico"
      ],
      [
        "panic",
        "pánico"
      ],
      [
        "photographic",
        "fotográfico"
      ],
      [
        "plastic",
        "plástico"
      ],
      [
        "poetic",
        "poético"
      ],
      [
        "political",
        "político"
      ],
      [
        "practical",
        "práctico"
      ],
      [
        "psychological",
        "psicológico"
      ],
      [
        "public",
        "público"
      ],
      [
        "rhythmic",
        "rítmico"
      ],
      [
        "robotic",
        "robótico"
      ],
      [
        "romantic",
        "romántico"
      ],
      [
        "scientific",
        "científico"
      ],
      [
        "specific",
        "específico"
      ],
      [
        "strategic",
        "estratégico"
      ],
      [
        "symbolic",
        "simbólico"
      ],
      [
        "systematic",
        "sistemático"
      ],
      [
        "technical",
        "técnico"
      ],
      [
        "theoretical",
        "teórico"
      ],
      [
        "toxic",
        "tóxico"
      ],
      [
        "tragic",
        "trágico"
      ],
      [
        "typical",
        "típico"
      ],
      [
        "volcanic",
        "volcánico"
      ]
    ]
  },
  "ive-ivo": {
    "id": "ive-ivo",
    "title": "-ive → -ivo / -iva",
    "explanation": "Many English adjectives ending in -ive have a related Spanish adjective ending in -ivo or -iva.",
    "listenLanguage": "es-ES",
    "words": [
      [
        "active",
        "activo"
      ],
      [
        "adaptive",
        "adaptativo"
      ],
      [
        "administrative",
        "administrativo"
      ],
      [
        "affirmative",
        "afirmativo"
      ],
      [
        "aggressive",
        "agresivo"
      ],
      [
        "alternative",
        "alternativo"
      ],
      [
        "attractive",
        "atractivo"
      ],
      [
        "collective",
        "colectivo"
      ],
      [
        "comparative",
        "comparativo"
      ],
      [
        "competitive",
        "competitivo"
      ],
      [
        "cooperative",
        "cooperativo"
      ],
      [
        "creative",
        "creativo"
      ],
      [
        "decisive",
        "decisivo"
      ],
      [
        "decorative",
        "decorativo"
      ],
      [
        "defensive",
        "defensivo"
      ],
      [
        "demonstrative",
        "demostrativo"
      ],
      [
        "descriptive",
        "descriptivo"
      ],
      [
        "distinctive",
        "distintivo"
      ],
      [
        "effective",
        "efectivo"
      ],
      [
        "excessive",
        "excesivo"
      ],
      [
        "exclusive",
        "exclusivo"
      ],
      [
        "executive",
        "ejecutivo"
      ],
      [
        "expansive",
        "expansivo"
      ],
      [
        "explosive",
        "explosivo"
      ],
      [
        "expressive",
        "expresivo"
      ],
      [
        "indicative",
        "indicativo"
      ],
      [
        "intensive",
        "intensivo"
      ],
      [
        "legislative",
        "legislativo"
      ],
      [
        "native",
        "nativo"
      ],
      [
        "negative",
        "negativo"
      ],
      [
        "objective",
        "objetivo"
      ],
      [
        "operative",
        "operativo"
      ],
      [
        "passive",
        "pasivo"
      ],
      [
        "positive",
        "positivo"
      ],
      [
        "preventive",
        "preventivo"
      ],
      [
        "primitive",
        "primitivo"
      ],
      [
        "productive",
        "productivo"
      ],
      [
        "progressive",
        "progresivo"
      ],
      [
        "reactive",
        "reactivo"
      ],
      [
        "relative",
        "relativo"
      ],
      [
        "representative",
        "representativo"
      ],
      [
        "restrictive",
        "restrictivo"
      ],
      [
        "selective",
        "selectivo"
      ],
      [
        "speculative",
        "especulativo"
      ],
      [
        "subjective",
        "subjetivo"
      ],
      [
        "successive",
        "sucesivo"
      ]
    ]
  },
  "ist-ista": {
    "id": "ist-ista",
    "title": "-ist → -ista",
    "explanation": "Many English nouns ending in -ist have a closely related Spanish noun ending in -ista.",
    "listenLanguage": "es-ES",
    "words": [
      [
        "activist",
        "activista"
      ],
      [
        "artist",
        "artista"
      ],
      [
        "capitalist",
        "capitalista"
      ],
      [
        "communist",
        "comunista"
      ],
      [
        "cyclist",
        "ciclista"
      ],
      [
        "dentist",
        "dentista"
      ],
      [
        "fascist",
        "fascista"
      ],
      [
        "feminist",
        "feminista"
      ],
      [
        "finalist",
        "finalista"
      ],
      [
        "florist",
        "florista"
      ],
      [
        "guitarist",
        "guitarrista"
      ],
      [
        "idealist",
        "idealista"
      ],
      [
        "linguist",
        "lingüista"
      ],
      [
        "materialist",
        "materialista"
      ],
      [
        "minimalist",
        "minimalista"
      ],
      [
        "modernist",
        "modernista"
      ],
      [
        "motorist",
        "motorista"
      ],
      [
        "nationalist",
        "nacionalista"
      ],
      [
        "novelist",
        "novelista"
      ],
      [
        "optimist",
        "optimista"
      ],
      [
        "pacifist",
        "pacifista"
      ],
      [
        "pessimist",
        "pesimista"
      ],
      [
        "pianist",
        "pianista"
      ],
      [
        "pluralist",
        "pluralista"
      ],
      [
        "realist",
        "realista"
      ],
      [
        "receptionist",
        "recepcionista"
      ],
      [
        "socialist",
        "socialista"
      ],
      [
        "soloist",
        "solista"
      ],
      [
        "specialist",
        "especialista"
      ],
      [
        "stylist",
        "estilista"
      ],
      [
        "tourist",
        "turista"
      ],
      [
        "violinist",
        "violinista"
      ]
    ]
  },
  "ance-encia": {
    "id": "ance-encia",
    "title": "-ance / -ence → -ancia / -encia",
    "explanation": "Many English nouns ending in -ance or -ence have a related Spanish noun ending in -ancia or -encia.",
    "listenLanguage": "es-ES",
    "words": [
      [
        "absence",
        "ausencia"
      ],
      [
        "abundance",
        "abundancia"
      ],
      [
        "assistance",
        "asistencia"
      ],
      [
        "audience",
        "audiencia"
      ],
      [
        "circumstance",
        "circunstancia"
      ],
      [
        "coincidence",
        "coincidencia"
      ],
      [
        "competence",
        "competencia"
      ],
      [
        "conference",
        "conferencia"
      ],
      [
        "conscience",
        "conciencia"
      ],
      [
        "consequence",
        "consecuencia"
      ],
      [
        "correspondence",
        "correspondencia"
      ],
      [
        "dependence",
        "dependencia"
      ],
      [
        "difference",
        "diferencia"
      ],
      [
        "distance",
        "distancia"
      ],
      [
        "elegance",
        "elegancia"
      ],
      [
        "evidence",
        "evidencia"
      ],
      [
        "excellence",
        "excelencia"
      ],
      [
        "existence",
        "existencia"
      ],
      [
        "experience",
        "experiencia"
      ],
      [
        "frequency",
        "frecuencia"
      ],
      [
        "ignorance",
        "ignorancia"
      ],
      [
        "importance",
        "importancia"
      ],
      [
        "independence",
        "independencia"
      ],
      [
        "influence",
        "influencia"
      ],
      [
        "innocence",
        "inocencia"
      ],
      [
        "instance",
        "instancia"
      ],
      [
        "intelligence",
        "inteligencia"
      ],
      [
        "obedience",
        "obediencia"
      ],
      [
        "patience",
        "paciencia"
      ],
      [
        "persistence",
        "persistencia"
      ],
      [
        "preference",
        "preferencia"
      ],
      [
        "presence",
        "presencia"
      ],
      [
        "relevance",
        "relevancia"
      ],
      [
        "resistance",
        "resistencia"
      ],
      [
        "substance",
        "sustancia"
      ],
      [
        "tolerance",
        "tolerancia"
      ],
      [
        "transcendence",
        "trascendencia"
      ],
      [
        "violence",
        "violencia"
      ]
    ]
  },
  "ism-ismo": {
    "id": "ism-ismo",
    "title": "-ism → -ismo",
    "explanation": "Many English nouns ending in -ism have a closely related Spanish form ending in -ismo.",
    "listenLanguage": "es-ES",
    "words": [
      [
        "activism",
        "activismo"
      ],
      [
        "alcoholism",
        "alcoholismo"
      ],
      [
        "anarchism",
        "anarquismo"
      ],
      [
        "atheism",
        "ateísmo"
      ],
      [
        "bilingualism",
        "bilingüismo"
      ],
      [
        "capitalism",
        "capitalismo"
      ],
      [
        "Catholicism",
        "catolicismo"
      ],
      [
        "colonialism",
        "colonialismo"
      ],
      [
        "communism",
        "comunismo"
      ],
      [
        "consumerism",
        "consumismo"
      ],
      [
        "cubism",
        "cubismo"
      ],
      [
        "dogmatism",
        "dogmatismo"
      ],
      [
        "egoism",
        "egoísmo"
      ],
      [
        "existentialism",
        "existencialismo"
      ],
      [
        "fascism",
        "fascismo"
      ],
      [
        "federalism",
        "federalismo"
      ],
      [
        "feminism",
        "feminismo"
      ],
      [
        "feudalism",
        "feudalismo"
      ],
      [
        "formalism",
        "formalismo"
      ],
      [
        "globalism",
        "globalismo"
      ],
      [
        "humanism",
        "humanismo"
      ],
      [
        "idealism",
        "idealismo"
      ],
      [
        "imperialism",
        "imperialismo"
      ],
      [
        "individualism",
        "individualismo"
      ],
      [
        "liberalism",
        "liberalismo"
      ],
      [
        "Marxism",
        "marxismo"
      ],
      [
        "materialism",
        "materialismo"
      ],
      [
        "mechanism",
        "mecanismo"
      ],
      [
        "minimalism",
        "minimalismo"
      ],
      [
        "modernism",
        "modernismo"
      ],
      [
        "nationalism",
        "nacionalismo"
      ],
      [
        "naturalism",
        "naturalismo"
      ],
      [
        "optimism",
        "optimismo"
      ],
      [
        "organism",
        "organismo"
      ],
      [
        "pacifism",
        "pacifismo"
      ],
      [
        "pessimism",
        "pesimismo"
      ],
      [
        "pluralism",
        "pluralismo"
      ],
      [
        "pragmatism",
        "pragmatismo"
      ],
      [
        "realism",
        "realismo"
      ],
      [
        "romanticism",
        "romanticismo"
      ],
      [
        "socialism",
        "socialismo"
      ],
      [
        "surrealism",
        "surrealismo"
      ],
      [
        "symbolism",
        "simbolismo"
      ],
      [
        "terrorism",
        "terrorismo"
      ],
      [
        "tourism",
        "turismo"
      ],
      [
        "traditionalism",
        "tradicionalismo"
      ],
      [
        "vegetarianism",
        "vegetarianismo"
      ]
    ]
  },
  "able-ible": {
    "id": "able-ible",
    "title": "-able / -ible → -able / -ible",
    "explanation": "Many English adjectives ending in -able or -ible have a similar Spanish cognate ending, though spelling can shift.",
    "listenLanguage": "es-ES",
    "words": [
      [
        "acceptable",
        "aceptable"
      ],
      [
        "accessible",
        "accesible"
      ],
      [
        "adaptable",
        "adaptable"
      ],
      [
        "admirable",
        "admirable"
      ],
      [
        "applicable",
        "aplicable"
      ],
      [
        "compatible",
        "compatible"
      ],
      [
        "considerable",
        "considerable"
      ],
      [
        "controllable",
        "controlable"
      ],
      [
        "debatable",
        "debatible"
      ],
      [
        "desirable",
        "deseable"
      ],
      [
        "detectable",
        "detectable"
      ],
      [
        "flexible",
        "flexible"
      ],
      [
        "formidable",
        "formidable"
      ],
      [
        "identifiable",
        "identificable"
      ],
      [
        "imaginable",
        "imaginable"
      ],
      [
        "incompatible",
        "incompatible"
      ],
      [
        "incredible",
        "increíble"
      ],
      [
        "inevitable",
        "inevitable"
      ],
      [
        "invisible",
        "invisible"
      ],
      [
        "legible",
        "legible"
      ],
      [
        "memorable",
        "memorable"
      ],
      [
        "possible",
        "posible"
      ],
      [
        "probable",
        "probable"
      ],
      [
        "questionable",
        "cuestionable"
      ],
      [
        "reasonable",
        "razonable"
      ],
      [
        "reversible",
        "reversible"
      ],
      [
        "sensible",
        "sensible"
      ],
      [
        "terrible",
        "terrible"
      ],
      [
        "variable",
        "variable"
      ],
      [
        "visible",
        "visible"
      ],
      [
        "vulnerable",
        "vulnerable"
      ]
    ]
  },
  "ant-ent": {
    "id": "ant-ent",
    "title": "-ant / -ent → -ante / -ente",
    "explanation": "Many English words ending in -ant or -ent have a related Spanish form ending in -ante or -ente.",
    "listenLanguage": "es-ES",
    "words": [
      [
        "abundant",
        "abundante"
      ],
      [
        "adolescent",
        "adolescente"
      ],
      [
        "apparent",
        "aparente"
      ],
      [
        "arrogant",
        "arrogante"
      ],
      [
        "brilliant",
        "brillante"
      ],
      [
        "competent",
        "competente"
      ],
      [
        "consistent",
        "consistente"
      ],
      [
        "constant",
        "constante"
      ],
      [
        "different",
        "diferente"
      ],
      [
        "distant",
        "distante"
      ],
      [
        "dominant",
        "dominante"
      ],
      [
        "elegant",
        "elegante"
      ],
      [
        "excellent",
        "excelente"
      ],
      [
        "frequent",
        "frecuente"
      ],
      [
        "ignorant",
        "ignorante"
      ],
      [
        "important",
        "importante"
      ],
      [
        "intelligent",
        "inteligente"
      ],
      [
        "persistent",
        "persistente"
      ],
      [
        "president",
        "presidente"
      ],
      [
        "relevant",
        "relevante"
      ],
      [
        "resident",
        "residente"
      ],
      [
        "resistant",
        "resistente"
      ],
      [
        "sufficient",
        "suficiente"
      ],
      [
        "transparent",
        "transparente"
      ],
      [
        "urgent",
        "urgente"
      ],
      [
        "vigilant",
        "vigilante"
      ]
    ]
  },
  "ize-izar": {
    "id": "ize-izar",
    "title": "-ize → -izar",
    "explanation": "Many English verbs ending in -ize have a related Spanish infinitive ending in -izar.",
    "listenLanguage": "es-ES",
    "words": [
      [
        "actualize",
        "actualizar"
      ],
      [
        "authorize",
        "autorizar"
      ],
      [
        "centralize",
        "centralizar"
      ],
      [
        "colonize",
        "colonizar"
      ],
      [
        "criminalize",
        "criminalizar"
      ],
      [
        "democratize",
        "democratizar"
      ],
      [
        "digitalize",
        "digitalizar"
      ],
      [
        "dramatize",
        "dramatizar"
      ],
      [
        "formalize",
        "formalizar"
      ],
      [
        "globalize",
        "globalizar"
      ],
      [
        "idealize",
        "idealizar"
      ],
      [
        "industrialize",
        "industrializar"
      ],
      [
        "legalize",
        "legalizar"
      ],
      [
        "localize",
        "localizar"
      ],
      [
        "materialize",
        "materializar"
      ],
      [
        "maximize",
        "maximizar"
      ],
      [
        "minimize",
        "minimizar"
      ],
      [
        "mobilize",
        "movilizar"
      ],
      [
        "modernize",
        "modernizar"
      ],
      [
        "normalize",
        "normalizar"
      ],
      [
        "optimize",
        "optimizar"
      ],
      [
        "organize",
        "organizar"
      ],
      [
        "personalize",
        "personalizar"
      ],
      [
        "polarize",
        "polarizar"
      ],
      [
        "popularize",
        "popularizar"
      ],
      [
        "privatize",
        "privatizar"
      ],
      [
        "regularize",
        "regularizar"
      ],
      [
        "specialize",
        "especializar"
      ],
      [
        "standardize",
        "estandarizar"
      ],
      [
        "symbolize",
        "simbolizar"
      ],
      [
        "synchronize",
        "sincronizar"
      ],
      [
        "systematize",
        "sistematizar"
      ],
      [
        "utilize",
        "utilizar"
      ],
      [
        "visualize",
        "visualizar"
      ],
      [
        "vocalize",
        "vocalizar"
      ]
    ]
  },
  "fy-ficar": {
    "id": "fy-ficar",
    "title": "-fy → -ficar",
    "explanation": "Many English verbs ending in -fy have a related Spanish verb ending in -ficar.",
    "listenLanguage": "es-ES",
    "words": [
      [
        "acidify",
        "acidificar"
      ],
      [
        "amplify",
        "amplificar"
      ],
      [
        "certify",
        "certificar"
      ],
      [
        "clarify",
        "clarificar"
      ],
      [
        "classify",
        "clasificar"
      ],
      [
        "codify",
        "codificar"
      ],
      [
        "diversify",
        "diversificar"
      ],
      [
        "electrify",
        "electrificar"
      ],
      [
        "exemplify",
        "ejemplificar"
      ],
      [
        "falsify",
        "falsificar"
      ],
      [
        "fortify",
        "fortificar"
      ],
      [
        "glorify",
        "glorificar"
      ],
      [
        "identify",
        "identificar"
      ],
      [
        "intensify",
        "intensificar"
      ],
      [
        "justify",
        "justificar"
      ],
      [
        "magnify",
        "magnificar"
      ],
      [
        "modify",
        "modificar"
      ],
      [
        "notify",
        "notificar"
      ],
      [
        "purify",
        "purificar"
      ],
      [
        "qualify",
        "cualificar"
      ],
      [
        "quantify",
        "cuantificar"
      ],
      [
        "ratify",
        "ratificar"
      ],
      [
        "rectify",
        "rectificar"
      ],
      [
        "simplify",
        "simplificar"
      ],
      [
        "solidify",
        "solidificar"
      ],
      [
        "specify",
        "especificar"
      ],
      [
        "stratify",
        "estratificar"
      ],
      [
        "unify",
        "unificar"
      ],
      [
        "verify",
        "verificar"
      ]
    ]
  },
  "al-al": {
    "id": "al-al",
    "title": "-al → -al",
    "explanation": "Many English words ending in -al keep the -al ending in Spanish, often with a small spelling change in the stem.",
    "listenLanguage": "es-ES",
    "words": [
      [
        "abdominal",
        "abdominal"
      ],
      [
        "accidental",
        "accidental"
      ],
      [
        "animal",
        "animal"
      ],
      [
        "annual",
        "anual"
      ],
      [
        "artificial",
        "artificial"
      ],
      [
        "capital",
        "capital"
      ],
      [
        "central",
        "central"
      ],
      [
        "cerebral",
        "cerebral"
      ],
      [
        "commercial",
        "comercial"
      ],
      [
        "cultural",
        "cultural"
      ],
      [
        "digital",
        "digital"
      ],
      [
        "electoral",
        "electoral"
      ],
      [
        "emotional",
        "emocional"
      ],
      [
        "essential",
        "esencial"
      ],
      [
        "federal",
        "federal"
      ],
      [
        "final",
        "final"
      ],
      [
        "formal",
        "formal"
      ],
      [
        "fundamental",
        "fundamental"
      ],
      [
        "general",
        "general"
      ],
      [
        "global",
        "global"
      ],
      [
        "horizontal",
        "horizontal"
      ],
      [
        "ideal",
        "ideal"
      ],
      [
        "industrial",
        "industrial"
      ],
      [
        "legal",
        "legal"
      ],
      [
        "liberal",
        "liberal"
      ],
      [
        "local",
        "local"
      ],
      [
        "manual",
        "manual"
      ],
      [
        "material",
        "material"
      ],
      [
        "mental",
        "mental"
      ],
      [
        "moral",
        "moral"
      ],
      [
        "municipal",
        "municipal"
      ],
      [
        "musical",
        "musical"
      ],
      [
        "national",
        "nacional"
      ],
      [
        "natural",
        "natural"
      ],
      [
        "normal",
        "normal"
      ],
      [
        "official",
        "oficial"
      ],
      [
        "oral",
        "oral"
      ],
      [
        "original",
        "original"
      ],
      [
        "personal",
        "personal"
      ],
      [
        "principal",
        "principal"
      ],
      [
        "professional",
        "profesional"
      ],
      [
        "regional",
        "regional"
      ],
      [
        "rural",
        "rural"
      ],
      [
        "social",
        "social"
      ],
      [
        "special",
        "especial"
      ],
      [
        "spiritual",
        "espiritual"
      ],
      [
        "structural",
        "estructural"
      ],
      [
        "traditional",
        "tradicional"
      ],
      [
        "tropical",
        "tropical"
      ],
      [
        "universal",
        "universal"
      ],
      [
        "vertical",
        "vertical"
      ],
      [
        "virtual",
        "virtual"
      ],
      [
        "visual",
        "visual"
      ]
    ]
  }
};
